import { v4 as uuidv4 } from "uuid";

export interface Question {
  id: string;
  text: string;
  options: string[];
  correctAnswer: string;
}

export const questionBank: Question[] = [
  {
    id: uuidv4(),
    text: "Which components of the nurse-client relationship is the nurse demonstrating? (Select all that apply)",
    options: [
      "Maintaining boundaries",
      "Client-centred care",
      "Protecting the client from abuse",
      "Therapeutic communication",
    ],
    correctAnswer: "Client-centred care",
  },
  {
    id: uuidv4(),
    text: "What, if anything, must the nurse do after giving a double dose of acetaminophen (Tylenol) to a client who only requires a single dose?",
    options: [
      "Ask a colleague to help assess the client",
      "Withhold the client's next dose of Tylenol",
      "Report the error as soon as possible",
      "Nothing, because this is an over-the-counter medication",
    ],
    correctAnswer: "Report the error as soon as possible",
  },
  {
    id: uuidv4(),
    text: "An RPN orders an RPN colleague to insert a urethral catheter into a newly admitted client. What should the RPN colleague do?",
    options: [
      "Confirm the order with a physician before proceeding with the intervention",
      "Accept the order and proceed with the intervention",
      "Consult with an RN before proceeding with the intervention",
      "Decline to accept the order",
    ],
    correctAnswer: "Decline to accept the order",
  },
  {
    id: uuidv4(),
    text: "A client writes to the College of Nurses of Ontario (CNO) stating that a nurse assaulted him during care. What action may CNO take in this situation?",
    options: [
      "Report the nurse to the employer",
      "Investigate the allegation",
      "Request that the nurse's employment be terminated",
      "Refer the complaint to local law enforcement",
    ],
    correctAnswer: "Investigate the allegation",
  },
  {
    id: uuidv4(),
    text: "Nursing jurisprudence primarily deals with:",
    options: [
      "Ethical principles in nursing",
      "Moral obligations of nurses",
      "Legal aspects governing nursing practice",
      "Administrative policies in hospitals",
    ],
    correctAnswer: "Legal aspects governing nursing practice",
  },
  {
    id: uuidv4(),
    text: "Law created by legislative bodies is known as:",
    options: ["Statutory law", "Common law", "Criminal law", "Civil law"],
    correctAnswer: "Statutory law",
  },
  {
    id: uuidv4(),
    text: "Law derived from court decisions and precedents is called:",
    options: [
      "Statutory law",
      "Common law",
      "Administrative law",
      "Constitutional law",
    ],
    correctAnswer: "Common law",
  },
  {
    id: uuidv4(),
    text: "Which law governs professional licensure and regulation of nurses?",
    options: ["Criminal law", "Civil law", "Administrative law", "Common law"],
    correctAnswer: "Administrative law",
  },
  {
    id: uuidv4(),
    text: "Threatening a patient with an injection without administering it is:",
    options: ["Assault", "Battery", "Negligence", "False imprisonment"],
    correctAnswer: "Assault",
  },
  {
    id: uuidv4(),
    text: "Administering an injection to a patient without consent constitutes:",
    options: ["Assault", "Battery", "Negligence", "Libel"],
    correctAnswer: "Battery",
  },
  {
    id: uuidv4(),
    text: "Detaining a patient against their will without legal authority is:",
    options: ["Negligence", "Battery", "False imprisonment", "Assault"],
    correctAnswer: "False imprisonment",
  },
  {
    id: uuidv4(),
    text: "Professional negligence by a nurse that results in patient harm is termed:",
    options: ["Tort", "Assault", "Malpractice", "Defamation"],
    correctAnswer: "Malpractice",
  },
  {
    id: uuidv4(),
    text: "Which element is NOT required to establish negligence?",
    options: [
      "Duty of care",
      "Breach of duty",
      "Harm to the patient",
      "Intent",
    ],
    correctAnswer: "Intent",
  },
  {
    id: uuidv4(),
    text: "Failure to administer prescribed medication is an example of:",
    options: ["Battery", "Assault", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The legal obligation of a nurse to provide care is called:",
    options: ["Standard care", "Duty of care", "Moral duty", "Ethical duty"],
    correctAnswer: "Duty of care",
  },
  {
    id: uuidv4(),
    text: "Which principle means 'do no harm'?",
    options: ["Beneficence", "Non-maleficence", "Justice", "Autonomy"],
    correctAnswer: "Non-maleficence",
  },
  {
    id: uuidv4(),
    text: "A nurse discussing patient information in public violates:",
    options: ["Justice", "Fidelity", "Confidentiality", "Accountability"],
    correctAnswer: "Confidentiality",
  },
  {
    id: uuidv4(),
    text: "Truthfulness in professional practice refers to:",
    options: ["Justice", "Veracity", "Autonomy", "Fidelity"],
    correctAnswer: "Veracity",
  },
  {
    id: uuidv4(),
    text: "Keeping promises made to patients is known as:",
    options: ["Veracity", "Justice", "Fidelity", "Accountability"],
    correctAnswer: "Fidelity",
  },
  {
    id: uuidv4(),
    text: "Which principle supports a patient's right to make decisions about care?",
    options: ["Beneficence", "Justice", "Autonomy", "Non-maleficence"],
    correctAnswer: "Autonomy",
  },
  {
    id: uuidv4(),
    text: "The doctrine that holds employers responsible for employees' actions is:",
    options: [
      "Res ipsa loquitur",
      "Stare decisis",
      "Vicarious liability",
      "Habeas corpus",
    ],
    correctAnswer: "Vicarious liability",
  },
  {
    id: uuidv4(),
    text: "'Res ipsa loquitur' means:",
    options: [
      "Let the master answer",
      "The thing speaks for itself",
      "Burden of proof",
      "Court authority",
    ],
    correctAnswer: "The thing speaks for itself",
  },
  {
    id: uuidv4(),
    text: "Which court usually hears malpractice cases?",
    options: [
      "Criminal court",
      "Supreme court",
      "Civil court",
      "Administrative tribunal",
    ],
    correctAnswer: "Civil court",
  },
  {
    id: uuidv4(),
    text: "Practicing nursing without a valid license is a:",
    options: [
      "Civil offense",
      "Ethical violation only",
      "Criminal offense",
      "Minor administrative error",
    ],
    correctAnswer: "Criminal offense",
  },
  {
    id: uuidv4(),
    text: "Ignorance of the law by a nurse is:",
    options: [
      "Acceptable defense",
      "Partial defense",
      "Never a defense",
      "Considered mitigating",
    ],
    correctAnswer: "Never a defense",
  },
  {
    id: uuidv4(),
    text: "Informed consent is INVALID when:",
    options: [
      "It is verbal",
      "Patient is illiterate",
      "It is obtained through coercion",
      "Witness is present",
    ],
    correctAnswer: "It is obtained through coercion",
  },
  {
    id: uuidv4(),
    text: "Which is essential for valid informed consent?",
    options: [
      "Written form only",
      "Family approval",
      "Patient understanding and voluntariness",
      "Nurse's explanation alone",
    ],
    correctAnswer: "Patient understanding and voluntariness",
  },
  {
    id: uuidv4(),
    text: "The nurse--patient relationship legally begins when:",
    options: [
      "Patient is admitted",
      "Consent is signed",
      "Nurse accepts responsibility for care",
      "Treatment is completed",
    ],
    correctAnswer: "Nurse accepts responsibility for care",
  },
  {
    id: uuidv4(),
    text: "The most effective legal protection for nurses is:",
    options: [
      "Apology",
      "Verbal reporting",
      "Accurate documentation",
      "Seniority",
    ],
    correctAnswer: "Accurate documentation",
  },
  {
    id: uuidv4(),
    text: "Which document has the highest legal value?",
    options: [
      "Shift report",
      "Nurse's personal notes",
      "Patient medical record",
      "Ward manual",
    ],
    correctAnswer: "Patient medical record",
  },
  {
    id: uuidv4(),
    text: "Altering patient records to hide mistakes is:",
    options: [
      "Ethical lapse only",
      "Administrative error",
      "Criminal misconduct",
      "Acceptable correction",
    ],
    correctAnswer: "Criminal misconduct",
  },
  {
    id: uuidv4(),
    text: "The statute of limitation refers to:",
    options: [
      "Duration of hospitalization",
      "Trial length",
      "Time limit to file a lawsuit",
      "License renewal period",
    ],
    correctAnswer: "Time limit to file a lawsuit",
  },
  {
    id: uuidv4(),
    text: "Which nursing action has the highest risk for litigation?",
    options: [
      "Bed making",
      "Patient education",
      "Medication administration",
      "Vital signs assessment",
    ],
    correctAnswer: "Medication administration",
  },
  {
    id: uuidv4(),
    text: "Failing to monitor a patient after surgery is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Discussing false spoken statements about a colleague constitutes:",
    options: ["Slander", "Libel", "Assault", "Negligence"],
    correctAnswer: "Slander",
  },
  {
    id: uuidv4(),
    text: "False written statements that damage reputation are called:",
    options: ["Assault", "Libel", "Negligence", "Battery"],
    correctAnswer: "Libel",
  },
  {
    id: uuidv4(),
    text: "Which law focuses on punishment of offenders?",
    options: ["Criminal law", "Civil law", "Administrative law", "Common law"],
    correctAnswer: "Criminal law",
  },
  {
    id: uuidv4(),
    text: "Which law focuses on compensation for injury?",
    options: [
      "Criminal law",
      "Civil law",
      "Administrative law",
      "Constitutional law",
    ],
    correctAnswer: "Civil law",
  },
  {
    id: uuidv4(),
    text: "Failure to report a notifiable disease is:",
    options: [
      "Ethical issue only",
      "Legal offense",
      "Optional action",
      "Administrative choice",
    ],
    correctAnswer: "Legal offense",
  },
  {
    id: uuidv4(),
    text: "The main aim of nursing licensure is to:",
    options: [
      "Control nurses",
      "Increase hospital revenue",
      "Protect the public",
      "Improve nurse salaries",
    ],
    correctAnswer: "Protect the public",
  },
  {
    id: uuidv4(),
    text: "A nurse is legally accountable for:",
    options: [
      "Doctor's orders only",
      "Own professional actions",
      "Hospital management decisions",
      "Patient choices",
    ],
    correctAnswer: "Own professional actions",
  },
  {
    id: uuidv4(),
    text: "Restraints may be applied legally only when:",
    options: [
      "Family requests",
      "Staff shortage exists",
      "Patient poses immediate danger",
      "Patient refuses treatment",
    ],
    correctAnswer: "Patient poses immediate danger",
  },
  {
    id: uuidv4(),
    text: "Restraining a patient without justification amounts to:",
    options: ["Assault", "Battery", "False imprisonment", "Negligence"],
    correctAnswer: "False imprisonment",
  },
  {
    id: uuidv4(),
    text: "Professional accountability means:",
    options: [
      "Avoiding mistakes",
      "Blaming colleagues",
      "Being answerable for one's actions",
      "Obeying superiors blindly",
    ],
    correctAnswer: "Being answerable for one's actions",
  },
  {
    id: uuidv4(),
    text: "Failure to hand over a patient properly at shift change is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which principle ensures fairness in healthcare delivery?",
    options: ["Autonomy", "Beneficence", "Justice", "Fidelity"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "Sharing patient photos on social media without consent is:",
    options: [
      "Acceptable education",
      "Ethical issue only",
      "Legal and ethical violation",
      "Protected expression",
    ],
    correctAnswer: "Legal and ethical violation",
  },
  {
    id: uuidv4(),
    text: "Which factor LEAST affects legal responsibility?",
    options: [
      "Scope of practice",
      "Level of training",
      "Personal beliefs",
      "Patient condition",
    ],
    correctAnswer: "Personal beliefs",
  },
  {
    id: uuidv4(),
    text: "A legal document ordering court appearance is called:",
    options: ["Affidavit", "Injunction", "Subpoena", "Verdict"],
    correctAnswer: "Subpoena",
  },
  {
    id: uuidv4(),
    text: "The nurse's obligation to act in the patient's best interest is:",
    options: ["Beneficence", "Justice", "Autonomy", "Fidelity"],
    correctAnswer: "Beneficence",
  },
  {
    id: uuidv4(),
    text: "Which nursing activity has the lowest legal risk?",
    options: [
      "IV therapy",
      "Blood transfusion",
      "Bed making",
      "Injection administration",
    ],
    correctAnswer: "Bed making",
  },
  {
    id: uuidv4(),
    text: "Malpractice insurance is intended to:",
    options: [
      "Prevent errors",
      "Replace competence",
      "Protect nurses from financial loss",
      "Punish negligence",
    ],
    correctAnswer: "Protect nurses from financial loss",
  },
  {
    id: uuidv4(),
    text: "Failure to follow standard nursing procedures may result in:",
    options: [
      "Ethical praise",
      "Promotion",
      "Legal liability",
      "License extension",
    ],
    correctAnswer: "Legal liability",
  },
  {
    id: uuidv4(),
    text: "Knowledge of nursing jurisprudence helps nurses to:",
    options: [
      "Avoid responsibility",
      "Replace ethics",
      "Practice safely within the law",
      "Challenge hospital authority",
    ],
    correctAnswer: "Practice safely within the law",
  },
  {
    id: uuidv4(),
    text: "A nurse who fails to check a patient's identity before administering medication commits:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which of the following best defines tort?",
    options: [
      "Criminal wrongdoing",
      "Civil wrong causing harm",
      "Ethical violation",
      "Administrative error",
    ],
    correctAnswer: "Civil wrong causing harm",
  },
  {
    id: uuidv4(),
    text: "The legal responsibility of a nurse to follow institutional policies falls under:",
    options: [
      "Criminal law",
      "Administrative law",
      "Civil law",
      "Constitutional law",
    ],
    correctAnswer: "Administrative law",
  },
  {
    id: uuidv4(),
    text: "Which is an intentional tort?",
    options: ["Negligence", "Malpractice", "Battery", "Omission"],
    correctAnswer: "Battery",
  },
  {
    id: uuidv4(),
    text: "Failing to raise bed rails for a confused patient is an example of:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The nurse's primary legal obligation is toward the:",
    options: ["Hospital", "Physician", "Patient", "Nursing council"],
    correctAnswer: "Patient",
  },
  {
    id: uuidv4(),
    text: "The concept that past court decisions influence future cases is known as:",
    options: [
      "Stare decisis",
      "Res ipsa loquitur",
      "Habeas corpus",
      "Vicarious liability",
    ],
    correctAnswer: "Stare decisis",
  },
  {
    id: uuidv4(),
    text: "Which of the following best protects patient rights?",
    options: [
      "Hospital policies",
      "Physician orders",
      "Patient bill of rights",
      "Nursing ethics",
    ],
    correctAnswer: "Patient bill of rights",
  },
  {
    id: uuidv4(),
    text: "A nurse administering the wrong drug but causing no harm is still liable for:",
    options: ["Assault", "Battery", "Negligence", "Libel"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Failure to document nursing care implies that the care was:",
    options: ["Inadequate", "Late", "Not done", "Illegal"],
    correctAnswer: "Not done",
  },
  {
    id: uuidv4(),
    text: "Which act most commonly results in malpractice litigation?",
    options: [
      "Poor communication",
      "Equipment failure",
      "Medication error",
      "Patient dissatisfaction",
    ],
    correctAnswer: "Medication error",
  },
  {
    id: uuidv4(),
    text: "A nurse refusing to care for a patient without arranging a replacement commits:",
    options: ["Battery", "Assault", "Abandonment", "Negligence"],
    correctAnswer: "Abandonment",
  },
  {
    id: uuidv4(),
    text: "The legal duty to report suspected child abuse is an example of:",
    options: [
      "Ethical duty",
      "Mandatory reporting",
      "Voluntary disclosure",
      "Confidential privilege",
    ],
    correctAnswer: "Mandatory reporting",
  },
  {
    id: uuidv4(),
    text: "Which patient has the right to refuse treatment?",
    options: [
      "Unconscious patient",
      "Mentally unstable patient",
      "Competent adult patient",
      "Minor patient",
    ],
    correctAnswer: "Competent adult patient",
  },
  {
    id: uuidv4(),
    text: "A nurse disclosing patient information to an unauthorized person commits:",
    options: ["Assault", "Battery", "Breach of confidentiality", "Negligence"],
    correctAnswer: "Breach of confidentiality",
  },
  {
    id: uuidv4(),
    text: "The nurse's scope of practice is determined by:",
    options: [
      "Hospital policy only",
      "Physician preference",
      "Nurse Practice Act",
      "Seniority",
    ],
    correctAnswer: "Nurse Practice Act",
  },
  {
    id: uuidv4(),
    text: "Failure to act when action is required is termed:",
    options: ["Commission", "Omission", "Assault", "Battery"],
    correctAnswer: "Omission",
  },
  {
    id: uuidv4(),
    text: "Administering care beyond one's competence is considered:",
    options: [
      "Ethical practice",
      "Professional growth",
      "Negligence",
      "Legal protection",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The Nurse Practice Act primarily exists to:",
    options: [
      "Punish nurses",
      "Protect nurses",
      "Protect the public",
      "Promote hospitals",
    ],
    correctAnswer: "Protect the public",
  },
  {
    id: uuidv4(),
    text: "Which principle ensures equal treatment of all patients?",
    options: ["Autonomy", "Beneficence", "Justice", "Fidelity"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "Accepting gifts that influence professional judgment violates:",
    options: ["Autonomy", "Justice", "Professional ethics", "Beneficence"],
    correctAnswer: "Professional ethics",
  },
  {
    id: uuidv4(),
    text: "Which of the following is a nurse's legal defense in malpractice cases?",
    options: [
      "Good intention",
      "Lack of experience",
      "Adherence to standard of care",
      "Apology",
    ],
    correctAnswer: "Adherence to standard of care",
  },
  {
    id: uuidv4(),
    text: "The patient's right to privacy is protected under:",
    options: ["Criminal law", "Administrative law", "Civil law", "Common law"],
    correctAnswer: "Civil law",
  },
  {
    id: uuidv4(),
    text: "Administering treatment without informed consent constitutes:",
    options: ["Negligence", "Battery", "Assault", "Defamation"],
    correctAnswer: "Battery",
  },
  {
    id: uuidv4(),
    text: "Which situation BEST demonstrates informed consent?",
    options: [
      "Family signs consent",
      "Nurse explains procedure",
      "Patient understands risks and agrees voluntarily",
      "Doctor signs form",
    ],
    correctAnswer: "Patient understands risks and agrees voluntarily",
  },
  {
    id: uuidv4(),
    text: "Failure to follow up abnormal vital signs is an example of:",
    options: ["Battery", "Assault", "Negligence", "Libel"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which record is admissible in court as legal evidence?",
    options: [
      "Nurse's diary",
      "Verbal report",
      "Patient's medical chart",
      "Shift handover note",
    ],
    correctAnswer: "Patient's medical chart",
  },
  {
    id: uuidv4(),
    text: "A nurse who follows an unsafe physician order without questioning is:",
    options: [
      "Protected legally",
      "Ethically right",
      "Legally liable",
      "Exempt from blame",
    ],
    correctAnswer: "Legally liable",
  },
  {
    id: uuidv4(),
    text: "Professional misconduct may lead to:",
    options: [
      "Promotion",
      "Commendation",
      "License suspension",
      "Salary increase",
    ],
    correctAnswer: "License suspension",
  },
  {
    id: uuidv4(),
    text: "The legal concept of foreseeability refers to:",
    options: [
      "Intent to harm",
      "Chance occurrence",
      "Predictable risk of harm",
      "Unavoidable error",
    ],
    correctAnswer: "Predictable risk of harm",
  },
  {
    id: uuidv4(),
    text: "Failure to maintain equipment resulting in injury constitutes:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The nurse's duty to act in emergencies is called:",
    options: ["Voluntary duty", "Moral duty", "Legal duty", "Optional duty"],
    correctAnswer: "Legal duty",
  },
  {
    id: uuidv4(),
    text: "Refusing to care for a patient based on race violates:",
    options: ["Autonomy", "Fidelity", "Justice", "Beneficence"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "Which action BEST reduces legal risk?",
    options: [
      "Experience alone",
      "Avoiding difficult patients",
      "Following established protocols",
      "Delegating care",
    ],
    correctAnswer: "Following established protocols",
  },
  {
    id: uuidv4(),
    text: "A nurse is obligated to report incompetent practice by colleagues due to:",
    options: [
      "Loyalty",
      "Friendship",
      "Legal and ethical duty",
      "Fear of punishment",
    ],
    correctAnswer: "Legal and ethical duty",
  },
  {
    id: uuidv4(),
    text: "Which is NOT part of informed consent?",
    options: ["Disclosure", "Understanding", "Nurse decision", "Voluntariness"],
    correctAnswer: "Nurse decision",
  },
  {
    id: uuidv4(),
    text: "Providing care outside employment hours without agreement is:",
    options: [
      "Mandatory",
      "Ethical duty",
      "Voluntary service",
      "Legal obligation",
    ],
    correctAnswer: "Voluntary service",
  },
  {
    id: uuidv4(),
    text: "The burden of proof in malpractice cases lies with the:",
    options: ["Nurse", "Hospital", "Plaintiff", "Licensing board"],
    correctAnswer: "Plaintiff",
  },
  {
    id: uuidv4(),
    text: "Which situation constitutes abandonment?",
    options: [
      "End of shift handover",
      "Emergency referral",
      "Leaving patient without arranging care",
      "Patient discharge",
    ],
    correctAnswer: "Leaving patient without arranging care",
  },
  {
    id: uuidv4(),
    text: "Failure to observe infection control measures may result in:",
    options: [
      "Praise",
      "Ethical approval",
      "Legal liability",
      "License extension",
    ],
    correctAnswer: "Legal liability",
  },
  {
    id: uuidv4(),
    text: "A nurse who witnesses abuse and fails to report may face:",
    options: ["Promotion", "Commendation", "Legal action", "Ethical reward"],
    correctAnswer: "Legal action",
  },
  {
    id: uuidv4(),
    text: "Which act is punishable under criminal law?",
    options: [
      "Breach of confidentiality",
      "Practicing without license",
      "Documentation error",
      "Late medication",
    ],
    correctAnswer: "Practicing without license",
  },
  {
    id: uuidv4(),
    text: "The nurse's accountability cannot be transferred when care is:",
    options: ["Supervised", "Delegated", "Improperly delegated", "Assigned"],
    correctAnswer: "Improperly delegated",
  },
  {
    id: uuidv4(),
    text: "Which is an example of civil liability?",
    options: ["Theft", "Murder", "Malpractice", "Assault with weapon"],
    correctAnswer: "Malpractice",
  },
  {
    id: uuidv4(),
    text: "Which principle obligates nurses to act in patients' best interest?",
    options: ["Beneficence", "Autonomy", "Justice", "Veracity"],
    correctAnswer: "Beneficence",
  },
  {
    id: uuidv4(),
    text: "Failure to comply with court summons may result in:",
    options: ["Promotion", "Discharge", "Contempt of court", "Warning"],
    correctAnswer: "Contempt of court",
  },
  {
    id: uuidv4(),
    text: "Professional boundaries are established to:",
    options: [
      "Restrict care",
      "Control nurses",
      "Protect patients and nurses",
      "Increase authority",
    ],
    correctAnswer: "Protect patients and nurses",
  },
  {
    id: uuidv4(),
    text: "Which factor MOST influences legal judgment in nursing cases?",
    options: [
      "Nurse's intention",
      "Years of experience",
      "Standard of care",
      "Personal belief",
    ],
    correctAnswer: "Standard of care",
  },
  {
    id: uuidv4(),
    text: "A nurse altering documentation after an incident commits:",
    options: [
      "Ethical breach only",
      "Minor offense",
      "Fraud",
      "Acceptable correction",
    ],
    correctAnswer: "Fraud",
  },
  {
    id: uuidv4(),
    text: "Understanding nursing jurisprudence enables nurses to:",
    options: [
      "Avoid ethics",
      "Challenge doctors",
      "Practice lawfully and safely",
      "Ignore policies",
    ],
    correctAnswer: "Practice lawfully and safely",
  },
  {
    id: uuidv4(),
    text: "Which legal concept means 'let the master answer'?",
    options: [
      "Stare decisis",
      "Res ipsa loquitur",
      "Respondeat superior",
      "Habeas corpus",
    ],
    correctAnswer: "Respondeat superior",
  },
  {
    id: uuidv4(),
    text: "Failure of a nurse to provide care that results in harm is:",
    options: [
      "Ethical dilemma",
      "Professional error",
      "Negligence",
      "Misconduct",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which element establishes a nurse--patient legal relationship?",
    options: [
      "Nurse presence",
      "Hospital admission",
      "Acceptance of assignment",
      "Patient diagnosis",
    ],
    correctAnswer: "Acceptance of assignment",
  },
  {
    id: uuidv4(),
    text: "Which document defines the legal scope of nursing practice?",
    options: [
      "Hospital policy",
      "Nursing ethics code",
      "Nurse Practice Act",
      "Employment contract",
    ],
    correctAnswer: "Nurse Practice Act",
  },
  {
    id: uuidv4(),
    text: "Administering medication without checking allergy history is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Failure to secure informed consent before surgery may result in:",
    options: ["Negligence only", "Battery", "Assault", "Libel"],
    correctAnswer: "Battery",
  },
  {
    id: uuidv4(),
    text: "The nurse's obligation to maintain competence is required by:",
    options: [
      "Hospital policy",
      "Patient demand",
      "Professional law and ethics",
      "Physician order",
    ],
    correctAnswer: "Professional law and ethics",
  },
  {
    id: uuidv4(),
    text: "A nurse who follows outdated procedures may be liable for:",
    options: ["Assault", "Battery", "Negligence", "Fraud"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The primary purpose of malpractice insurance is to:",
    options: [
      "Prevent errors",
      "Increase salary",
      "Cover legal and financial costs",
      "Replace competence",
    ],
    correctAnswer: "Cover legal and financial costs",
  },
  {
    id: uuidv4(),
    text: "Failure to recognize and act on patient deterioration is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which situation demonstrates abandonment?",
    options: [
      "Referring patient to specialist",
      "Completing shift with handover",
      "Leaving unit without arranging care",
      "Patient discharge",
    ],
    correctAnswer: "Leaving unit without arranging care",
  },
  {
    id: uuidv4(),
    text: "A nurse is legally required to report which case?",
    options: [
      "Adult depression",
      "Chronic illness",
      "Suspected child abuse",
      "Minor injury",
    ],
    correctAnswer: "Suspected child abuse",
  },
  {
    id: uuidv4(),
    text: "Which legal term refers to harm caused by failure to act?",
    options: ["Commission", "Omission", "Battery", "Assault"],
    correctAnswer: "Omission",
  },
  {
    id: uuidv4(),
    text: "Which act is considered professional misconduct?",
    options: [
      "Asking for assistance",
      "Continuing education",
      "Practicing under the influence of alcohol",
      "Documenting care",
    ],
    correctAnswer: "Practicing under the influence of alcohol",
  },
  {
    id: uuidv4(),
    text: "Failure to identify a patient before a procedure is:",
    options: [
      "Ethical lapse",
      "Administrative error",
      "Negligence",
      "Legal compliance",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The right of a patient to access their medical record is supported by:",
    options: [
      "Criminal law",
      "Administrative law",
      "Civil law",
      "Constitutional law",
    ],
    correctAnswer: "Civil law",
  },
  {
    id: uuidv4(),
    text: "Which nursing act requires the highest legal accountability?",
    options: [
      "Health education",
      "Bed bath",
      "Medication administration",
      "Patient transfer",
    ],
    correctAnswer: "Medication administration",
  },
  {
    id: uuidv4(),
    text: "A nurse sharing patient data for research without consent commits:",
    options: [
      "Ethical violation only",
      "Breach of confidentiality",
      "Negligence",
      "Defamation",
    ],
    correctAnswer: "Breach of confidentiality",
  },
  {
    id: uuidv4(),
    text: "Which factor is MOST important in legal judgment of nursing care?",
    options: [
      "Nurse intention",
      "Hospital reputation",
      "Standard of care",
      "Patient opinion",
    ],
    correctAnswer: "Standard of care",
  },
  {
    id: uuidv4(),
    text: "Which action violates patient autonomy?",
    options: [
      "Explaining procedures",
      "Offering alternatives",
      "Forcing treatment on a competent patient",
      "Answering questions",
    ],
    correctAnswer: "Forcing treatment on a competent patient",
  },
  {
    id: uuidv4(),
    text: "Failure to comply with infection control standards may lead to:",
    options: [
      "Praise",
      "Ethical commendation",
      "Legal liability",
      "Salary increase",
    ],
    correctAnswer: "Legal liability",
  },
  {
    id: uuidv4(),
    text: "A nurse administering expired medication commits:",
    options: ["Assault", "Battery", "Negligence", "Libel"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which court handles disciplinary action against nurses?",
    options: [
      "Criminal court",
      "Civil court",
      "Administrative tribunal",
      "Supreme court",
    ],
    correctAnswer: "Administrative tribunal",
  },
  {
    id: uuidv4(),
    text: "Which principle requires fairness in distributing healthcare resources?",
    options: ["Autonomy", "Beneficence", "Justice", "Fidelity"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "A nurse refusing care to an HIV patient violates:",
    options: ["Beneficence", "Autonomy", "Justice", "Veracity"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "Which act may result in suspension of nursing license?",
    options: [
      "Late documentation",
      "Gross professional misconduct",
      "Heavy workload",
      "Staff shortage",
    ],
    correctAnswer: "Gross professional misconduct",
  },
  {
    id: uuidv4(),
    text: "Which statement best defines malpractice?",
    options: [
      "Ethical wrongdoing",
      "Administrative failure",
      "Professional negligence causing harm",
      "Intentional injury",
    ],
    correctAnswer: "Professional negligence causing harm",
  },
  {
    id: uuidv4(),
    text: "Failure to clarify unclear physician orders is:",
    options: [
      "Proper practice",
      "Ethical compliance",
      "Negligence",
      "Legal defense",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The nurse's duty to protect patients from harm refers to:",
    options: ["Autonomy", "Non-maleficence", "Justice", "Veracity"],
    correctAnswer: "Non-maleficence",
  },
  {
    id: uuidv4(),
    text: "Administering care outside scope of practice leads to:",
    options: [
      "Promotion",
      "Ethical recognition",
      "Legal liability",
      "Automatic dismissal",
    ],
    correctAnswer: "Legal liability",
  },
  {
    id: uuidv4(),
    text: "Which legal doctrine places burden of proof on plaintiff?",
    options: [
      "Respondeat superior",
      "Stare decisis",
      "Negligence law",
      "Habeas corpus",
    ],
    correctAnswer: "Negligence law",
  },
  {
    id: uuidv4(),
    text: "Which nursing action BEST demonstrates accountability?",
    options: [
      "Delegating tasks",
      "Blaming workload",
      "Accepting responsibility for actions",
      "Avoiding documentation",
    ],
    correctAnswer: "Accepting responsibility for actions",
  },
  {
    id: uuidv4(),
    text: "A nurse who falsifies time records commits:",
    options: ["Ethical breach only", "Minor misconduct", "Fraud", "Negligence"],
    correctAnswer: "Fraud",
  },
  {
    id: uuidv4(),
    text: "Which patient can legally refuse treatment?",
    options: [
      "Unconscious patient",
      "Mentally incompetent patient",
      "Competent adult patient",
      "Minor without guardian",
    ],
    correctAnswer: "Competent adult patient",
  },
  {
    id: uuidv4(),
    text: "Which action ensures legal safety during delegation?",
    options: [
      "Assigning complex tasks",
      "Avoiding supervision",
      "Delegating within scope and competence",
      "Delegating to reduce workload",
    ],
    correctAnswer: "Delegating within scope and competence",
  },
  {
    id: uuidv4(),
    text: "Which type of consent is implied by patient cooperation?",
    options: [
      "Written consent",
      "Express consent",
      "Implied consent",
      "Proxy consent",
    ],
    correctAnswer: "Implied consent",
  },
  {
    id: uuidv4(),
    text: "Failure to report workplace violence may lead to:",
    options: [
      "Commendation",
      "Neutral outcome",
      "Legal consequences",
      "Promotion",
    ],
    correctAnswer: "Legal consequences",
  },
  {
    id: uuidv4(),
    text: "Which situation is MOST likely to lead to litigation?",
    options: [
      "Near miss",
      "Minor error",
      "Severe injury due to negligence",
      "Patient dissatisfaction",
    ],
    correctAnswer: "Severe injury due to negligence",
  },
  {
    id: uuidv4(),
    text: "Which principle supports telling the truth to patients?",
    options: ["Fidelity", "Justice", "Veracity", "Beneficence"],
    correctAnswer: "Veracity",
  },
  {
    id: uuidv4(),
    text: "Refusing to follow unsafe orders protects the nurse under:",
    options: [
      "Criminal law",
      "Administrative policy",
      "Standard of care",
      "Hospital loyalty",
    ],
    correctAnswer: "Standard of care",
  },
  {
    id: uuidv4(),
    text: "Which act constitutes civil liability?",
    options: [
      "Theft",
      "Assault with weapon",
      "Breach of confidentiality",
      "Murder",
    ],
    correctAnswer: "Breach of confidentiality",
  },
  {
    id: uuidv4(),
    text: "The nurse's duty ends when:",
    options: [
      "Shift ends",
      "Patient sleeps",
      "Care is properly handed over",
      "Doctor arrives",
    ],
    correctAnswer: "Care is properly handed over",
  },
  {
    id: uuidv4(),
    text: "Which of the following is an example of intentional tort?",
    options: [
      "Medication error",
      "Failure to assess",
      "False imprisonment",
      "Omission",
    ],
    correctAnswer: "False imprisonment",
  },
  {
    id: uuidv4(),
    text: "Which record is the strongest legal evidence of nursing care?",
    options: [
      "Verbal handover",
      "Nurse diary",
      "Patient medical record",
      "Incident report",
    ],
    correctAnswer: "Patient medical record",
  },
  {
    id: uuidv4(),
    text: "Failure to maintain professional boundaries may result in:",
    options: [
      "Promotion",
      "Commendation",
      "Legal and disciplinary action",
      "License extension",
    ],
    correctAnswer: "Legal and disciplinary action",
  },
  {
    id: uuidv4(),
    text: "Which nursing act violates patient confidentiality?",
    options: [
      "Consulting healthcare team",
      "Discussing patient details in public",
      "Documenting care",
      "Reporting abuse",
    ],
    correctAnswer: "Discussing patient details in public",
  },
  {
    id: uuidv4(),
    text: "Which legal principle ensures employers are responsible for nurses' acts?",
    options: [
      "Stare decisis",
      "Vicarious liability",
      "Habeas corpus",
      "Res ipsa loquitur",
    ],
    correctAnswer: "Vicarious liability",
  },
  {
    id: uuidv4(),
    text: "Which nurse action demonstrates beneficence?",
    options: [
      "Acting in the patient's best interest",
      "Respecting patient refusal",
      "Telling the truth",
      "Maintaining confidentiality",
    ],
    correctAnswer: "Acting in the patient's best interest",
  },
  {
    id: uuidv4(),
    text: "Failure to monitor IV therapy may result in:",
    options: ["Praise", "Ethical approval", "Negligence", "Legal immunity"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Nursing jurisprudence primarily helps nurses to:",
    options: [
      "Avoid supervision",
      "Replace ethics",
      "Understand legal responsibilities in practice",
      "Challenge administration",
    ],
    correctAnswer: "Understand legal responsibilities in practice",
  },
  {
    id: uuidv4(),
    text: "A nurse who fails to obtain informed consent before a procedure commits:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Battery",
  },
  {
    id: uuidv4(),
    text: "Which legal principle means 'the thing speaks for itself'?",
    options: [
      "Stare decisis",
      "Res ipsa loquitur",
      "Respondeat superior",
      "Habeas corpus",
    ],
    correctAnswer: "Res ipsa loquitur",
  },
  {
    id: uuidv4(),
    text: "A nurse delegating tasks remains legally responsible when delegation is:",
    options: ["Proper", "Supervised", "Improper", "Voluntary"],
    correctAnswer: "Improper",
  },
  {
    id: uuidv4(),
    text: "The right of patients to make decisions about their care is known as:",
    options: ["Justice", "Beneficence", "Autonomy", "Fidelity"],
    correctAnswer: "Autonomy",
  },
  {
    id: uuidv4(),
    text: "Administering medication without verifying physician's order is:",
    options: [
      "Ethical practice",
      "Legal protection",
      "Negligence",
      "Beneficence",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which is an example of omission?",
    options: [
      "Giving wrong medication",
      "Failure to administer prescribed medication",
      "Verbal threat",
      "Physical restraint",
    ],
    correctAnswer: "Failure to administer prescribed medication",
  },
  {
    id: uuidv4(),
    text: "Which factor is MOST important in determining malpractice?",
    options: [
      "Nurse's years of experience",
      "Intent to harm",
      "Deviation from standard of care",
      "Patient satisfaction",
    ],
    correctAnswer: "Deviation from standard of care",
  },
  {
    id: uuidv4(),
    text: "Which law governs the renewal and suspension of nursing licenses?",
    options: ["Criminal law", "Civil law", "Administrative law", "Common law"],
    correctAnswer: "Administrative law",
  },
  {
    id: uuidv4(),
    text: "Leaving a patient without ensuring continuity of care is:",
    options: [
      "Ethical dilemma",
      "Proper practice",
      "Abandonment",
      "Beneficence",
    ],
    correctAnswer: "Abandonment",
  },
  {
    id: uuidv4(),
    text: "Which nurse action best demonstrates legal accountability?",
    options: [
      "Following doctor blindly",
      "Avoiding difficult patients",
      "Documenting care accurately",
      "Delegating all tasks",
    ],
    correctAnswer: "Documenting care accurately",
  },
  {
    id: uuidv4(),
    text: "A nurse revealing patient information to the media commits:",
    options: [
      "Ethical praise",
      "Professional autonomy",
      "Breach of confidentiality",
      "Beneficence",
    ],
    correctAnswer: "Breach of confidentiality",
  },
  {
    id: uuidv4(),
    text: "Which court hears criminal cases involving nurses?",
    options: [
      "Criminal court",
      "Civil court",
      "Administrative tribunal",
      "Nursing council",
    ],
    correctAnswer: "Criminal court",
  },
  {
    id: uuidv4(),
    text: "Which principle requires nurses to be truthful with patients?",
    options: ["Justice", "Fidelity", "Veracity", "Autonomy"],
    correctAnswer: "Veracity",
  },
  {
    id: uuidv4(),
    text: "Failure to follow infection control protocols constitutes:",
    options: [
      "Ethical compliance",
      "Administrative success",
      "Negligence",
      "Beneficence",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "A nurse is legally obligated to refuse care only when:",
    options: [
      "Workload is heavy",
      "Patient is demanding",
      "Care is beyond scope of practice",
      "Shift is ending",
    ],
    correctAnswer: "Care is beyond scope of practice",
  },
  {
    id: uuidv4(),
    text: "Which of the following is an intentional tort?",
    options: ["Omission", "Negligence", "Assault", "Malpractice"],
    correctAnswer: "Assault",
  },
  {
    id: uuidv4(),
    text: "Which document outlines patients' legal rights?",
    options: [
      "Hospital rules",
      "Nursing ethics code",
      "Patient bill of rights",
      "Employment contract",
    ],
    correctAnswer: "Patient bill of rights",
  },
  {
    id: uuidv4(),
    text: "Failure to monitor vital signs after surgery is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which principle obligates nurses to avoid harm?",
    options: ["Autonomy", "Non-maleficence", "Justice", "Veracity"],
    correctAnswer: "Non-maleficence",
  },
  {
    id: uuidv4(),
    text: "Which scenario BEST demonstrates battery?",
    options: [
      "Threatening to give injection",
      "Giving injection without consent",
      "Forgetting medication",
      "Discussing patient care",
    ],
    correctAnswer: "Giving injection without consent",
  },
  {
    id: uuidv4(),
    text: "The nurse's duty to report unsafe practice is based on:",
    options: [
      "Loyalty",
      "Friendship",
      "Legal and ethical obligation",
      "Personal belief",
    ],
    correctAnswer: "Legal and ethical obligation",
  },
  {
    id: uuidv4(),
    text: "Which action places a nurse at highest risk for litigation?",
    options: [
      "Patient education",
      "Bed bathing",
      "Medication administration",
      "Vital sign monitoring",
    ],
    correctAnswer: "Medication administration",
  },
  {
    id: uuidv4(),
    text: "Which legal term refers to holding employers liable for employees' acts?",
    options: [
      "Stare decisis",
      "Vicarious liability",
      "Res ipsa loquitur",
      "Habeas corpus",
    ],
    correctAnswer: "Vicarious liability",
  },
  {
    id: uuidv4(),
    text: "The nurse--patient relationship ends when:",
    options: [
      "Patient recovers",
      "Nurse leaves unit",
      "Care is properly transferred",
      "Physician arrives",
    ],
    correctAnswer: "Care is properly transferred",
  },
  {
    id: uuidv4(),
    text: "Which action violates professional boundaries?",
    options: [
      "Providing emotional support",
      "Explaining procedures",
      "Accepting expensive gifts from patient",
      "Educating patient",
    ],
    correctAnswer: "Accepting expensive gifts from patient",
  },
  {
    id: uuidv4(),
    text: "Failure to clarify illegible medication order is:",
    options: [
      "Ethical compliance",
      "Professional autonomy",
      "Negligence",
      "Legal defense",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which legal term refers to time allowed to file a lawsuit?",
    options: ["Subpoena", "Verdict", "Statute of limitation", "Injunction"],
    correctAnswer: "Statute of limitation",
  },
  {
    id: uuidv4(),
    text: "Which factor LEAST affects legal responsibility?",
    options: [
      "Scope of practice",
      "Training",
      "Personal opinion",
      "Patient condition",
    ],
    correctAnswer: "Personal opinion",
  },
  {
    id: uuidv4(),
    text: "A nurse may restrain a patient only when:",
    options: [
      "Family requests",
      "Patient refuses care",
      "Immediate danger exists",
      "Staff is inadequate",
    ],
    correctAnswer: "Immediate danger exists",
  },
  {
    id: uuidv4(),
    text: "Which principle ensures fairness in healthcare delivery?",
    options: ["Autonomy", "Beneficence", "Justice", "Fidelity"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "Which nurse action constitutes fraud?",
    options: [
      "Late documentation",
      "Incomplete report",
      "Falsifying patient records",
      "Verbal handover",
    ],
    correctAnswer: "Falsifying patient records",
  },
  {
    id: uuidv4(),
    text: "Failure to obtain consent before touching a patient is:",
    options: ["Negligence", "Battery", "Assault", "Defamation"],
    correctAnswer: "Battery",
  },
  {
    id: uuidv4(),
    text: "Which nurse behavior best demonstrates professionalism?",
    options: [
      "Ignoring policies",
      "Avoiding documentation",
      "Practicing within legal scope",
      "Delegating excessively",
    ],
    correctAnswer: "Practicing within legal scope",
  },
  {
    id: uuidv4(),
    text: "The nurse's responsibility for delegated tasks includes:",
    options: [
      "Total transfer of accountability",
      "No supervision",
      "Ongoing supervision and evaluation",
      "Avoiding follow-up",
    ],
    correctAnswer: "Ongoing supervision and evaluation",
  },
  {
    id: uuidv4(),
    text: "Which situation violates confidentiality?",
    options: [
      "Reporting communicable disease",
      "Discussing care with healthcare team",
      "Sharing patient details with friends",
      "Documenting patient care",
    ],
    correctAnswer: "Sharing patient details with friends",
  },
  {
    id: uuidv4(),
    text: "Which type of consent is assumed in emergency situations?",
    options: [
      "Express consent",
      "Written consent",
      "Implied consent",
      "Proxy consent",
    ],
    correctAnswer: "Implied consent",
  },
  {
    id: uuidv4(),
    text: "Which principle requires nurses to keep promises?",
    options: ["Veracity", "Justice", "Fidelity", "Autonomy"],
    correctAnswer: "Fidelity",
  },
  {
    id: uuidv4(),
    text: "A nurse may be disciplined for professional misconduct by:",
    options: [
      "Civil court",
      "Criminal court",
      "Nursing regulatory body",
      "Patient family",
    ],
    correctAnswer: "Nursing regulatory body",
  },
  {
    id: uuidv4(),
    text: "Which action BEST prevents malpractice claims?",
    options: [
      "Apologizing to patients",
      "Relying on experience",
      "Adhering to standards of care",
      "Avoiding difficult cases",
    ],
    correctAnswer: "Adhering to standards of care",
  },
  {
    id: uuidv4(),
    text: "Which nurse action demonstrates beneficence?",
    options: [
      "Respecting patient refusal",
      "Telling the truth",
      "Acting in patient's best interest",
      "Maintaining confidentiality",
    ],
    correctAnswer: "Acting in patient's best interest",
  },
  {
    id: uuidv4(),
    text: "A nurse ignoring a patient's call bell may be guilty of:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which law deals with compensation for injury or damage?",
    options: [
      "Criminal law",
      "Civil law",
      "Administrative law",
      "Constitutional law",
    ],
    correctAnswer: "Civil law",
  },
  {
    id: uuidv4(),
    text: "The nurse's legal accountability is limited by:",
    options: [
      "Experience",
      "Employer policies",
      "Scope of practice",
      "Patient demands",
    ],
    correctAnswer: "Scope of practice",
  },
  {
    id: uuidv4(),
    text: "Which nurse action is considered abandonment?",
    options: [
      "Referring patient",
      "Ending shift with handover",
      "Leaving patient without arranging care",
      "Discharging patient",
    ],
    correctAnswer: "Leaving patient without arranging care",
  },
  {
    id: uuidv4(),
    text: "Failure to report medication error is:",
    options: [
      "Ethical practice",
      "Legal protection",
      "Professional misconduct",
      "Beneficence",
    ],
    correctAnswer: "Professional misconduct",
  },
  {
    id: uuidv4(),
    text: "Which principle emphasizes doing good for patients?",
    options: ["Beneficence", "Autonomy", "Justice", "Veracity"],
    correctAnswer: "Beneficence",
  },
  {
    id: uuidv4(),
    text: "Which nurse action violates autonomy?",
    options: [
      "Educating patient",
      "Offering options",
      "Forcing treatment on competent patient",
      "Answering questions",
    ],
    correctAnswer: "Forcing treatment on competent patient",
  },
  {
    id: uuidv4(),
    text: "Which document provides legal proof of care given?",
    options: [
      "Nurse's memory",
      "Shift report",
      "Patient medical record",
      "Verbal communication",
    ],
    correctAnswer: "Patient medical record",
  },
  {
    id: uuidv4(),
    text: "Failure to supervise delegated care may result in:",
    options: ["Promotion", "Commendation", "Legal liability", "Immunity"],
    correctAnswer: "Legal liability",
  },
  {
    id: uuidv4(),
    text: "Nursing jurisprudence mainly focuses on:",
    options: [
      "Moral philosophy",
      "Hospital administration",
      "Legal responsibilities of nurses",
      "Patient psychology",
    ],
    correctAnswer: "Legal responsibilities of nurses",
  },
  {
    id: uuidv4(),
    text: "Which nurse action best demonstrates legal competence?",
    options: [
      "Acting independently always",
      "Ignoring hospital policy",
      "Practicing within scope of practice",
      "Relying on experience alone",
    ],
    correctAnswer: "Practicing within scope of practice",
  },
  {
    id: uuidv4(),
    text: "Failure to prevent a patient from falling when risk was known is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which legal principle places responsibility on employers for employee actions?",
    options: [
      "Stare decisis",
      "Respondeat superior",
      "Habeas corpus",
      "Injunction",
    ],
    correctAnswer: "Respondeat superior",
  },
  {
    id: uuidv4(),
    text: "Which action by a nurse is an intentional tort?",
    options: [
      "Forgetting to chart medication",
      "Failure to monitor vitals",
      "Restraining a patient without justification",
      "Delay in treatment",
    ],
    correctAnswer: "Restraining a patient without justification",
  },
  {
    id: uuidv4(),
    text: "The most important legal protection for a nurse is:",
    options: [
      "Experience",
      "Good intentions",
      "Accurate and timely documentation",
      "Supervisor support",
    ],
    correctAnswer: "Accurate and timely documentation",
  },
  {
    id: uuidv4(),
    text: "Which element must be present to establish negligence?",
    options: ["Intent", "Consent", "Breach of duty", "Apology"],
    correctAnswer: "Breach of duty",
  },
  {
    id: uuidv4(),
    text: "Failure to report a colleague's unsafe practice violates:",
    options: ["Fidelity", "Veracity", "Legal and ethical duty", "Beneficence"],
    correctAnswer: "Legal and ethical duty",
  },
  {
    id: uuidv4(),
    text: "A nurse performing a procedure without competence is guilty of:",
    options: ["Beneficence", "Autonomy", "Negligence", "Justice"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which situation best illustrates abandonment?",
    options: [
      "Patient transfer",
      "Emergency referral",
      "Leaving a patient without arranging care",
      "Shift handover",
    ],
    correctAnswer: "Leaving a patient without arranging care",
  },
  {
    id: uuidv4(),
    text: "Which type of consent is assumed in life-threatening emergencies?",
    options: [
      "Written consent",
      "Express consent",
      "Implied consent",
      "Proxy consent",
    ],
    correctAnswer: "Implied consent",
  },
  {
    id: uuidv4(),
    text: "Which legal principle means 'the facts speak for themselves'?",
    options: [
      "Respondeat superior",
      "Res ipsa loquitur",
      "Stare decisis",
      "Habeas corpus",
    ],
    correctAnswer: "Res ipsa loquitur",
  },
  {
    id: uuidv4(),
    text: "Failure to adhere to standard nursing protocols constitutes:",
    options: [
      "Ethical success",
      "Professional autonomy",
      "Negligence",
      "Beneficence",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which principle obligates nurses to act in the patient's best interest?",
    options: ["Beneficence", "Autonomy", "Justice", "Veracity"],
    correctAnswer: "Beneficence",
  },
  {
    id: uuidv4(),
    text: "Administering medication to the wrong patient is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The Nurse Practice Act primarily serves to:",
    options: [
      "Protect nurses",
      "Promote hospitals",
      "Protect the public",
      "Regulate salaries",
    ],
    correctAnswer: "Protect the public",
  },
  {
    id: uuidv4(),
    text: "A nurse who discloses patient information without consent commits:",
    options: [
      "Ethical praise",
      "Professional growth",
      "Breach of confidentiality",
      "Beneficence",
    ],
    correctAnswer: "Breach of confidentiality",
  },
  {
    id: uuidv4(),
    text: "Which act constitutes professional misconduct?",
    options: [
      "Seeking clarification",
      "Continuing education",
      "Practicing while intoxicated",
      "Accurate documentation",
    ],
    correctAnswer: "Practicing while intoxicated",
  },
  {
    id: uuidv4(),
    text: "The nurse's legal accountability for patient care ends when:",
    options: [
      "Shift ends",
      "Patient improves",
      "Care is properly handed over",
      "Physician arrives",
    ],
    correctAnswer: "Care is properly handed over",
  },
  {
    id: uuidv4(),
    text: "Which law deals primarily with punishment of offenders?",
    options: ["Criminal law", "Civil law", "Administrative law", "Common law"],
    correctAnswer: "Criminal law",
  },
  {
    id: uuidv4(),
    text: "Which legal concept refers to time limit for filing a lawsuit?",
    options: ["Injunction", "Subpoena", "Statute of limitation", "Verdict"],
    correctAnswer: "Statute of limitation",
  },
  {
    id: uuidv4(),
    text: "Which nurse action violates patient autonomy?",
    options: [
      "Educating patient",
      "Offering treatment options",
      "Forcing treatment on competent patient",
      "Respecting refusal",
    ],
    correctAnswer: "Forcing treatment on competent patient",
  },
  {
    id: uuidv4(),
    text: "Which nursing action carries the highest legal risk?",
    options: [
      "Bed making",
      "Health education",
      "Medication administration",
      "Vital signs assessment",
    ],
    correctAnswer: "Medication administration",
  },
  {
    id: uuidv4(),
    text: "Which court handles disciplinary actions against nurses?",
    options: [
      "Criminal court",
      "Civil court",
      "Administrative tribunal",
      "Supreme court",
    ],
    correctAnswer: "Administrative tribunal",
  },
  {
    id: uuidv4(),
    text: "Which ethical-legal principle requires truth telling?",
    options: ["Fidelity", "Justice", "Veracity", "Autonomy"],
    correctAnswer: "Veracity",
  },
  {
    id: uuidv4(),
    text: "Failure to monitor a patient after surgery is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which factor LEAST affects legal responsibility in nursing?",
    options: [
      "Scope of practice",
      "Level of competence",
      "Personal belief",
      "Patient condition",
    ],
    correctAnswer: "Personal belief",
  },
  {
    id: uuidv4(),
    text: "A nurse may legally restrain a patient only when:",
    options: [
      "Family insists",
      "Patient refuses care",
      "Immediate danger exists",
      "Staffing is inadequate",
    ],
    correctAnswer: "Immediate danger exists",
  },
  {
    id: uuidv4(),
    text: "Which legal concept holds nurses responsible for their own actions?",
    options: [
      "Vicarious liability",
      "Res ipsa loquitur",
      "Professional accountability",
      "Respondeat superior",
    ],
    correctAnswer: "Professional accountability",
  },
  {
    id: uuidv4(),
    text: "Which act constitutes fraud?",
    options: [
      "Delayed documentation",
      "Incomplete charting",
      "Falsifying patient records",
      "Verbal handover",
    ],
    correctAnswer: "Falsifying patient records",
  },
  {
    id: uuidv4(),
    text: "Which principle emphasizes fairness in healthcare delivery?",
    options: ["Beneficence", "Autonomy", "Justice", "Fidelity"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "Failure to clarify unclear physician orders results in:",
    options: [
      "Ethical compliance",
      "Legal protection",
      "Negligence",
      "Beneficence",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which nursing behavior best demonstrates professionalism?",
    options: [
      "Ignoring policies",
      "Avoiding documentation",
      "Practicing within legal boundaries",
      "Delegating all care",
    ],
    correctAnswer: "Practicing within legal boundaries",
  },
  {
    id: uuidv4(),
    text: "Which action violates professional boundaries?",
    options: [
      "Explaining procedures",
      "Emotional support",
      "Accepting expensive gifts from patients",
      "Patient education",
    ],
    correctAnswer: "Accepting expensive gifts from patients",
  },
  {
    id: uuidv4(),
    text: "Which law governs licensure, suspension, and discipline of nurses?",
    options: ["Criminal law", "Civil law", "Administrative law", "Common law"],
    correctAnswer: "Administrative law",
  },
  {
    id: uuidv4(),
    text: "Which nurse action is an example of omission?",
    options: [
      "Administering wrong drug",
      "Failure to administer prescribed medication",
      "Verbal threat",
      "Physical restraint",
    ],
    correctAnswer: "Failure to administer prescribed medication",
  },
  {
    id: uuidv4(),
    text: "Which document is the strongest legal evidence of nursing care?",
    options: [
      "Nurse's notes alone",
      "Incident report",
      "Patient medical record",
      "Shift handover",
    ],
    correctAnswer: "Patient medical record",
  },
  {
    id: uuidv4(),
    text: "Which principle requires nurses to keep promises to patients?",
    options: ["Justice", "Veracity", "Fidelity", "Autonomy"],
    correctAnswer: "Fidelity",
  },
  {
    id: uuidv4(),
    text: "A nurse who leaves the ward without handing over care commits:",
    options: ["Ethical compliance", "Beneficence", "Abandonment", "Autonomy"],
    correctAnswer: "Abandonment",
  },
  {
    id: uuidv4(),
    text: "Which act is punishable under civil law?",
    options: ["Theft", "Murder", "Malpractice", "Armed robbery"],
    correctAnswer: "Malpractice",
  },
  {
    id: uuidv4(),
    text: "Which nursing action best prevents legal action?",
    options: [
      "Relying on experience",
      "Apologizing after errors",
      "Adhering to standard of care",
      "Avoiding complex cases",
    ],
    correctAnswer: "Adhering to standard of care",
  },
  {
    id: uuidv4(),
    text: "Failure to maintain patient safety devices may result in:",
    options: ["Praise", "Ethical reward", "Negligence", "Immunity"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which nurse action violates confidentiality?",
    options: [
      "Consulting healthcare team",
      "Reporting notifiable disease",
      "Discussing patient information in public",
      "Documenting care",
    ],
    correctAnswer: "Discussing patient information in public",
  },
  {
    id: uuidv4(),
    text: "Which principle supports patient decision-making rights?",
    options: ["Beneficence", "Justice", "Autonomy", "Fidelity"],
    correctAnswer: "Autonomy",
  },
  {
    id: uuidv4(),
    text: "Which nursing act is considered battery?",
    options: [
      "Threatening injection",
      "Administering injection without consent",
      "Delayed medication",
      "Poor documentation",
    ],
    correctAnswer: "Administering injection without consent",
  },
  {
    id: uuidv4(),
    text: "Which action demonstrates veracity?",
    options: [
      "Keeping promises",
      "Telling the truth to patients",
      "Acting in patient's interest",
      "Respecting refusal",
    ],
    correctAnswer: "Telling the truth to patients",
  },
  {
    id: uuidv4(),
    text: "Which nurse behavior may lead to license revocation?",
    options: [
      "Heavy workload",
      "Minor documentation error",
      "Gross professional misconduct",
      "Staff shortage",
    ],
    correctAnswer: "Gross professional misconduct",
  },
  {
    id: uuidv4(),
    text: "Which legal concept allows courts to follow previous rulings?",
    options: ["Stare decisis", "Habeas corpus", "Injunction", "Subpoena"],
    correctAnswer: "Stare decisis",
  },
  {
    id: uuidv4(),
    text: "Failure to assess patient condition before intervention is:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which principle emphasizes doing no harm?",
    options: ["Beneficence", "Non-maleficence", "Justice", "Veracity"],
    correctAnswer: "Non-maleficence",
  },
  {
    id: uuidv4(),
    text: "Nursing jurisprudence equips nurses to:",
    options: [
      "Avoid ethical dilemmas",
      "Replace clinical judgment",
      "Practice safely within legal boundaries",
      "Ignore hospital policies",
    ],
    correctAnswer: "Practice safely within legal boundaries",
  },
  {
    id: uuidv4(),
    text: "Which nurse action BEST reflects adherence to the law?",
    options: [
      "Acting based on experience alone",
      "Ignoring hospital protocols",
      "Following established standards of care",
      "Relying on physician authority",
    ],
    correctAnswer: "Following established standards of care",
  },
  {
    id: uuidv4(),
    text: "Failure to recognize a patient's deteriorating condition constitutes:",
    options: ["Assault", "Battery", "Negligence", "Defamation"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which legal doctrine holds employers liable for employees' actions?",
    options: [
      "Res ipsa loquitur",
      "Respondeat superior",
      "Stare decisis",
      "Habeas corpus",
    ],
    correctAnswer: "Respondeat superior",
  },
  {
    id: uuidv4(),
    text: "Administering care without patient consent is legally considered:",
    options: ["Negligence", "Battery", "Assault", "Defamation"],
    correctAnswer: "Battery",
  },
  {
    id: uuidv4(),
    text: "Which action demonstrates professional accountability?",
    options: [
      "Avoiding documentation",
      "Blaming colleagues",
      "Accepting responsibility for actions",
      "Delegating all care",
    ],
    correctAnswer: "Accepting responsibility for actions",
  },
  {
    id: uuidv4(),
    text: "Which factor MOST determines malpractice liability?",
    options: [
      "Nurse's intention",
      "Hospital reputation",
      "Deviation from standard of care",
      "Patient dissatisfaction",
    ],
    correctAnswer: "Deviation from standard of care",
  },
  {
    id: uuidv4(),
    text: "Failure to document nursing interventions implies care was:",
    options: ["Delayed", "Inadequate", "Not done", "Illegal"],
    correctAnswer: "Not done",
  },
  {
    id: uuidv4(),
    text: "Which law governs nurse licensure and disciplinary actions?",
    options: ["Criminal law", "Civil law", "Administrative law", "Common law"],
    correctAnswer: "Administrative law",
  },
  {
    id: uuidv4(),
    text: "Leaving a patient without proper handover is termed:",
    options: ["Ethical dilemma", "Beneficence", "Abandonment", "Autonomy"],
    correctAnswer: "Abandonment",
  },
  {
    id: uuidv4(),
    text: "Which type of consent applies when a patient cooperates with care?",
    options: [
      "Written consent",
      "Express consent",
      "Implied consent",
      "Proxy consent",
    ],
    correctAnswer: "Implied consent",
  },
  {
    id: uuidv4(),
    text: "Which legal principle means 'the facts speak for themselves'?",
    options: [
      "Stare decisis",
      "Res ipsa loquitur",
      "Respondeat superior",
      "Injunction",
    ],
    correctAnswer: "Res ipsa loquitur",
  },
  {
    id: uuidv4(),
    text: "Administering medication beyond scope of practice is:",
    options: ["Beneficence", "Autonomy", "Negligence", "Justice"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "The primary goal of the Nurse Practice Act is to:",
    options: [
      "Protect nurses",
      "Regulate hospitals",
      "Protect the public",
      "Promote nursing education",
    ],
    correctAnswer: "Protect the public",
  },
  {
    id: uuidv4(),
    text: "Which nurse action violates patient confidentiality?",
    options: [
      "Reporting notifiable disease",
      "Discussing care with team",
      "Sharing patient details on social media",
      "Documenting care",
    ],
    correctAnswer: "Sharing patient details on social media",
  },
  {
    id: uuidv4(),
    text: "Failure to monitor a restrained patient results in:",
    options: ["Ethical compliance", "Beneficence", "Negligence", "Autonomy"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which legal principle requires truthfulness in nursing practice?",
    options: ["Justice", "Fidelity", "Veracity", "Beneficence"],
    correctAnswer: "Veracity",
  },
  {
    id: uuidv4(),
    text: "Which action BEST prevents malpractice lawsuits?",
    options: [
      "Apologizing after errors",
      "Avoiding complex cases",
      "Adhering to standards of care",
      "Working overtime",
    ],
    correctAnswer: "Adhering to standards of care",
  },
  {
    id: uuidv4(),
    text: "Which act is considered an intentional tort?",
    options: ["Omission", "Malpractice", "Assault", "Negligence"],
    correctAnswer: "Assault",
  },
  {
    id: uuidv4(),
    text: "Which court hears malpractice cases?",
    options: [
      "Criminal court",
      "Civil court",
      "Administrative tribunal",
      "Supreme court",
    ],
    correctAnswer: "Civil court",
  },
  {
    id: uuidv4(),
    text: "Failure to clarify unclear medication orders constitutes:",
    options: [
      "Ethical compliance",
      "Professional autonomy",
      "Negligence",
      "Legal defense",
    ],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which principle obligates nurses to do good for patients?",
    options: ["Beneficence", "Autonomy", "Justice", "Fidelity"],
    correctAnswer: "Beneficence",
  },
  {
    id: uuidv4(),
    text: "Which nursing activity carries the highest legal risk?",
    options: [
      "Bed making",
      "Patient education",
      "Medication administration",
      "Vital signs monitoring",
    ],
    correctAnswer: "Medication administration",
  },
  {
    id: uuidv4(),
    text: "Which factor LEAST influences legal judgment?",
    options: [
      "Scope of practice",
      "Competence",
      "Personal belief",
      "Patient condition",
    ],
    correctAnswer: "Personal belief",
  },
  {
    id: uuidv4(),
    text: "Which legal term refers to time allowed to initiate legal action?",
    options: ["Subpoena", "Verdict", "Statute of limitation", "Injunction"],
    correctAnswer: "Statute of limitation",
  },
  {
    id: uuidv4(),
    text: "Which nurse action demonstrates respect for patient autonomy?",
    options: [
      "Forcing treatment",
      "Withholding information",
      "Honoring informed refusal",
      "Making decisions for patient",
    ],
    correctAnswer: "Honoring informed refusal",
  },
  {
    id: uuidv4(),
    text: "Failure to follow infection prevention measures is:",
    options: ["Beneficence", "Justice", "Negligence", "Autonomy"],
    correctAnswer: "Negligence",
  },
  {
    id: uuidv4(),
    text: "Which action constitutes fraud?",
    options: [
      "Late documentation",
      "Incomplete notes",
      "Falsifying patient records",
      "Verbal report",
    ],
    correctAnswer: "Falsifying patient records",
  },
  {
    id: uuidv4(),
    text: "Which principle ensures fairness in care delivery?",
    options: ["Autonomy", "Beneficence", "Justice", "Veracity"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "Which nurse behavior violates professional boundaries?",
    options: [
      "Providing health education",
      "Emotional support",
      "Accepting large gifts from patients",
      "Explaining procedures",
    ],
    correctAnswer: "Accepting large gifts from patients",
  },
  {
    id: uuidv4(),
    text: "Which type of consent is valid in emergency situations?",
    options: [
      "Written consent",
      "Express consent",
      "Implied consent",
      "Proxy consent",
    ],
    correctAnswer: "Implied consent",
  },
  {
    id: uuidv4(),
    text: "Failure to supervise delegated care may result in:",
    options: ["Promotion", "Commendation", "Legal liability", "Immunity"],
    correctAnswer: "Legal liability",
  },
  {
    id: uuidv4(),
    text: "Which legal concept refers to nurses being answerable for their actions?",
    options: [
      "Respondeat superior",
      "Vicarious liability",
      "Professional accountability",
      "Stare decisis",
    ],
    correctAnswer: "Professional accountability",
  },
  {
    id: uuidv4(),
    text: "Which act violates patient confidentiality?",
    options: [
      "Reporting abuse",
      "Consulting healthcare team",
      "Discussing patient information in public areas",
      "Documenting care",
    ],
    correctAnswer: "Discussing patient information in public areas",
  },
  {
    id: uuidv4(),
    text: "Which principle requires nurses to keep promises?",
    options: ["Veracity", "Justice", "Fidelity", "Autonomy"],
    correctAnswer: "Fidelity",
  },
  {
    id: uuidv4(),
    text: "A nurse who practices while intoxicated commits:",
    options: [
      "Ethical practice",
      "Beneficence",
      "Professional misconduct",
      "Autonomy",
    ],
    correctAnswer: "Professional misconduct",
  },
  {
    id: uuidv4(),
    text: "Which nurse action demonstrates non-maleficence?",
    options: [
      "Acting in patient's interest",
      "Avoiding harm to patient",
      "Telling the truth",
      "Respecting decisions",
    ],
    correctAnswer: "Avoiding harm to patient",
  },
  {
    id: uuidv4(),
    text: "Which nursing action constitutes abandonment?",
    options: [
      "Referring patient",
      "Ending shift after handover",
      "Leaving patient without arranging care",
      "Transferring patient",
    ],
    correctAnswer: "Leaving patient without arranging care",
  },
  {
    id: uuidv4(),
    text: "Which document has the greatest legal importance?",
    options: [
      "Shift report",
      "Nurse's diary",
      "Patient medical record",
      "Incident log",
    ],
    correctAnswer: "Patient medical record",
  },
  {
    id: uuidv4(),
    text: "Which principle supports equal treatment of patients?",
    options: ["Beneficence", "Autonomy", "Justice", "Veracity"],
    correctAnswer: "Justice",
  },
  {
    id: uuidv4(),
    text: "Which action violates informed consent?",
    options: [
      "Explaining risks",
      "Allowing questions",
      "Performing procedure without consent",
      "Documenting consent",
    ],
    correctAnswer: "Performing procedure without consent",
  },
  {
    id: uuidv4(),
    text: "Which nurse action is most defensible legally?",
    options: [
      "Acting independently",
      "Ignoring protocol",
      "Following evidence-based practice",
      "Relying on experience",
    ],
    correctAnswer: "Following evidence-based practice",
  },
  {
    id: uuidv4(),
    text: "Failure to protect patient privacy may lead to:",
    options: ["Commendation", "Ethical reward", "Legal action", "Promotion"],
    correctAnswer: "Legal action",
  },
  {
    id: uuidv4(),
    text: "Which legal concept refers to duty to act?",
    options: ["Voluntary duty", "Moral duty", "Legal duty", "Optional duty"],
    correctAnswer: "Legal duty",
  },
  {
    id: uuidv4(),
    text: "Which action constitutes battery?",
    options: [
      "Threatening to inject",
      "Injecting without consent",
      "Forgetting medication",
      "Delayed treatment",
    ],
    correctAnswer: "Injecting without consent",
  },
  {
    id: uuidv4(),
    text: "Which principle supports honesty in communication?",
    options: ["Fidelity", "Justice", "Veracity", "Beneficence"],
    correctAnswer: "Veracity",
  },
  {
    id: uuidv4(),
    text: "Failure to report a notifiable disease is:",
    options: [
      "Ethical lapse only",
      "Legal offense",
      "Optional duty",
      "Administrative preference",
    ],
    correctAnswer: "Legal offense",
  },
  {
    id: uuidv4(),
    text: "Which nurse behavior may lead to license suspension?",
    options: [
      "Minor error",
      "Late documentation",
      "Gross negligence",
      "High workload",
    ],
    correctAnswer: "Gross negligence",
  },
  {
    id: uuidv4(),
    text: "Which legal principle ensures employers may be held liable?",
    options: [
      "Stare decisis",
      "Vicarious liability",
      "Habeas corpus",
      "Injunction",
    ],
    correctAnswer: "Vicarious liability",
  },
  {
    id: uuidv4(),
    text: "Which nurse action demonstrates beneficence?",
    options: [
      "Acting in the patient's best interest",
      "Respecting refusal",
      "Telling the truth",
      "Maintaining confidentiality",
    ],
    correctAnswer: "Acting in the patient's best interest",
  },
  {
    id: uuidv4(),
    text: "Nursing jurisprudence helps nurses to:",
    options: [
      "Avoid ethical codes",
      "Replace clinical skills",
      "Understand and apply legal principles in practice",
      "Ignore hospital rules",
    ],
    correctAnswer: "Understand and apply legal principles in practice",
  },
];
