import { v4 as uuidv4 } from "uuid";

export interface Question {
  id: string;
  text: string;
  options: string[];
  correctAnswer: string;
}

export const questionBank: Question[] = [
  // SHOCK QUESTIONS 1-40
  {
    id: uuidv4(),
    text: "Shock is best defined as:",
    options: [
      "Sudden loss of consciousness",
      "Failure of the heart to pump blood",
      "Inadequate tissue perfusion leading to cellular hypoxia",
      "Sudden drop in blood pressure",
    ],
    correctAnswer: "Inadequate tissue perfusion leading to cellular hypoxia",
  },
  {
    id: uuidv4(),
    text: "The earliest compensatory mechanism in hypovolemic shock is:",
    options: [
      "Decreased heart rate",
      "Peripheral vasoconstriction",
      "Increased urine output",
      "Reduced respiratory rate",
    ],
    correctAnswer: "Peripheral vasoconstriction",
  },
  {
    id: uuidv4(),
    text: "Which type of shock is caused by severe allergic reactions?",
    options: ["Septic", "Cardiogenic", "Neurogenic", "Anaphylactic"],
    correctAnswer: "Anaphylactic",
  },
  {
    id: uuidv4(),
    text: "A hallmark sign of cardiogenic shock is:",
    options: [
      "Warm flushed skin",
      "Bradycardia",
      "Pulmonary edema",
      "Increased urine output",
    ],
    correctAnswer: "Pulmonary edema",
  },
  {
    id: uuidv4(),
    text: "The most common cause of hypovolemic shock in adults is:",
    options: ["Burns", "Vomiting", "Hemorrhage", "Diarrhea"],
    correctAnswer: "Hemorrhage",
  },
  {
    id: uuidv4(),
    text: "Which laboratory finding is expected in septic shock?",
    options: [
      "Low white blood cell count",
      "Elevated serum lactate",
      "Decreased ESR",
      "Increased hemoglobin",
    ],
    correctAnswer: "Elevated serum lactate",
  },
  {
    id: uuidv4(),
    text: "Cold, clammy skin is most characteristic of:",
    options: [
      "Septic shock",
      "Hypovolemic shock",
      "Neurogenic shock",
      "Anaphylactic shock",
    ],
    correctAnswer: "Hypovolemic shock",
  },
  {
    id: uuidv4(),
    text: "The primary goal in the management of shock is to:",
    options: [
      "Reduce anxiety",
      "Maintain consciousness",
      "Restore tissue perfusion",
      "Increase body temperature",
    ],
    correctAnswer: "Restore tissue perfusion",
  },
  {
    id: uuidv4(),
    text: "Which IV fluid is most commonly used initially in shock?",
    options: [
      "Dextrose 5%",
      "Colloid solution",
      "Blood products",
      "Isotonic crystalloids",
    ],
    correctAnswer: "Isotonic crystalloids",
  },
  {
    id: uuidv4(),
    text: "In neurogenic shock, hypotension occurs due to:",
    options: [
      "Fluid loss",
      "Cardiac pump failure",
      "Loss of sympathetic tone",
      "Sepsis",
    ],
    correctAnswer: "Loss of sympathetic tone",
  },
  {
    id: uuidv4(),
    text: "A patient with shock has decreased urine output primarily because of:",
    options: [
      "Renal failure",
      "Reduced renal perfusion",
      "Bladder obstruction",
      "Increased ADH inhibition",
    ],
    correctAnswer: "Reduced renal perfusion",
  },
  {
    id: uuidv4(),
    text: "Which finding differentiates septic shock from hypovolemic shock?",
    options: [
      "Tachycardia",
      "Hypotension",
      "Warm flushed skin in early stage",
      "Oliguria",
    ],
    correctAnswer: "Warm flushed skin in early stage",
  },
  {
    id: uuidv4(),
    text: "The most sensitive indicator of shock resolution is:",
    options: [
      "Blood pressure",
      "Heart rate",
      "Urine output",
      "Respiratory rate",
    ],
    correctAnswer: "Urine output",
  },
  {
    id: uuidv4(),
    text: "Disseminated intravascular coagulation (DIC) is most commonly associated with:",
    options: [
      "Hypovolemic shock",
      "Cardiogenic shock",
      "Septic shock",
      "Neurogenic shock",
    ],
    correctAnswer: "Septic shock",
  },
  {
    id: uuidv4(),
    text: "Which drug is commonly used as a vasopressor in shock?",
    options: ["Morphine", "Furosemide", "Norepinephrine", "Diazepam"],
    correctAnswer: "Norepinephrine",
  },
  {
    id: uuidv4(),
    text: "In anaphylactic shock, the drug of choice is:",
    options: ["Hydrocortisone", "Diphenhydramine", "Epinephrine", "Salbutamol"],
    correctAnswer: "Epinephrine",
  },
  {
    id: uuidv4(),
    text: "Which acid-base imbalance is commonly seen in prolonged shock?",
    options: [
      "Respiratory alkalosis",
      "Metabolic alkalosis",
      "Metabolic acidosis",
      "Respiratory acidosis",
    ],
    correctAnswer: "Metabolic acidosis",
  },
  {
    id: uuidv4(),
    text: "The priority nursing action in a patient with suspected shock is to:",
    options: [
      "Obtain blood samples",
      "Administer antibiotics",
      "Ensure airway and oxygenation",
      "Insert urinary catheter",
    ],
    correctAnswer: "Ensure airway and oxygenation",
  },
  {
    id: uuidv4(),
    text: "Which organ is most sensitive to hypoxia during shock?",
    options: ["Liver", "Kidney", "Brain", "Skin"],
    correctAnswer: "Brain",
  },
  {
    id: uuidv4(),
    text: "A decreased central venous pressure (CVP) is seen in:",
    options: [
      "Cardiogenic shock",
      "Hypovolemic shock",
      "Septic shock",
      "Obstructive shock",
    ],
    correctAnswer: "Hypovolemic shock",
  },
  {
    id: uuidv4(),
    text: "The compensatory stage of shock is characterized by:",
    options: [
      "Multi-organ failure",
      "Activation of sympathetic nervous system",
      "Irreversible cell damage",
      "Severe hypotension",
    ],
    correctAnswer: "Activation of sympathetic nervous system",
  },
  {
    id: uuidv4(),
    text: "Which shock type presents with bradycardia instead of tachycardia?",
    options: ["Septic", "Cardiogenic", "Neurogenic", "Hypovolemic"],
    correctAnswer: "Neurogenic",
  },
  {
    id: uuidv4(),
    text: "The primary cause of cardiogenic shock is:",
    options: [
      "Hemorrhage",
      "Infection",
      "Myocardial infarction",
      "Spinal cord injury",
    ],
    correctAnswer: "Myocardial infarction",
  },
  {
    id: uuidv4(),
    text: "A rising serum lactate indicates:",
    options: [
      "Improved perfusion",
      "Anaerobic metabolism",
      "Renal recovery",
      "Respiratory alkalosis",
    ],
    correctAnswer: "Anaerobic metabolism",
  },
  {
    id: uuidv4(),
    text: "Which nursing diagnosis has the highest priority in shock?",
    options: [
      "Anxiety",
      "Risk for infection",
      "Ineffective tissue perfusion",
      "Impaired mobility",
    ],
    correctAnswer: "Ineffective tissue perfusion",
  },
  {
    id: uuidv4(),
    text: "Shock becomes irreversible primarily due to:",
    options: [
      "Hypotension",
      "Cellular and organ damage",
      "Bradycardia",
      "Hypoglycemia",
    ],
    correctAnswer: "Cellular and organ damage",
  },
  {
    id: uuidv4(),
    text: "Which assessment finding suggests worsening shock?",
    options: [
      "Increasing urine output",
      "Falling blood pressure despite fluids",
      "Warm extremities",
      "Improved mental status",
    ],
    correctAnswer: "Falling blood pressure despite fluids",
  },
  {
    id: uuidv4(),
    text: "Which hormone increases during shock to conserve water?",
    options: [
      "Insulin",
      "Aldosterone",
      "Antidiuretic hormone (ADH)",
      "Thyroxine",
    ],
    correctAnswer: "Antidiuretic hormone (ADH)",
  },
  {
    id: uuidv4(),
    text: "Oxygen therapy in shock aims to:",
    options: [
      "Reduce anxiety",
      "Increase tissue oxygen delivery",
      "Lower heart rate",
      "Decrease blood pressure",
    ],
    correctAnswer: "Increase tissue oxygen delivery",
  },
  {
    id: uuidv4(),
    text: "The definitive treatment of shock depends on:",
    options: ["Severity", "Age", "Underlying cause", "Gender"],
    correctAnswer: "Underlying cause",
  },
  {
    id: uuidv4(),
    text: "A patient in shock with bounding pulse and fever is likely experiencing:",
    options: [
      "Hypovolemic shock",
      "Cardiogenic shock",
      "Septic shock (early stage)",
      "Neurogenic shock",
    ],
    correctAnswer: "Septic shock (early stage)",
  },
  {
    id: uuidv4(),
    text: "Which parameter best reflects renal perfusion?",
    options: [
      "Blood pressure",
      "Heart rate",
      "Urine output",
      "Oxygen saturation",
    ],
    correctAnswer: "Urine output",
  },
  {
    id: uuidv4(),
    text: "Which complication is common in prolonged shock?",
    options: [
      "Hypertension",
      "Acute kidney injury",
      "Hyperglycemia",
      "Bradycardia",
    ],
    correctAnswer: "Acute kidney injury",
  },
  {
    id: uuidv4(),
    text: "In shock, capillary refill time is typically:",
    options: ["Less than 1 second", "Normal", "Prolonged", "Absent"],
    correctAnswer: "Prolonged",
  },
  {
    id: uuidv4(),
    text: "The initial management of hemorrhagic shock includes:",
    options: ["Diuretics", "Antibiotics", "Control of bleeding", "Steroids"],
    correctAnswer: "Control of bleeding",
  },
  {
    id: uuidv4(),
    text: "Which sign indicates poor cerebral perfusion in shock?",
    options: [
      "Hypertension",
      "Altered level of consciousness",
      "Bradycardia",
      "Hyperthermia",
    ],
    correctAnswer: "Altered level of consciousness",
  },
  {
    id: uuidv4(),
    text: "In obstructive shock, cardiac output is reduced due to:",
    options: [
      "Fluid loss",
      "Mechanical obstruction to blood flow",
      "Infection",
      "Myocardial infarction",
    ],
    correctAnswer: "Mechanical obstruction to blood flow",
  },
  {
    id: uuidv4(),
    text: "Which patient is at highest risk of septic shock?",
    options: [
      "Young adult",
      "Immunocompromised patient",
      "Athlete",
      "Pregnant woman",
    ],
    correctAnswer: "Immunocompromised patient",
  },
  {
    id: uuidv4(),
    text: "Which electrolyte imbalance may occur in shock?",
    options: [
      "Hypercalcemia",
      "Hyperkalemia",
      "Hypophosphatemia",
      "Hypernatremia",
    ],
    correctAnswer: "Hyperkalemia",
  },
  {
    id: uuidv4(),
    text: "The most reliable sign of effective shock management is:",
    options: [
      "Normal temperature",
      "Improved mental status and urine output",
      "Reduced pain",
      "Decreased anxiety",
    ],
    correctAnswer: "Improved mental status and urine output",
  },
  // CPR QUESTIONS 41-70
  {
    id: uuidv4(),
    text: "The first step in Basic Life Support (BLS) is to:",
    options: [
      "Start chest compressions",
      "Ensure scene safety",
      "Check pulse",
      "Give rescue breaths",
    ],
    correctAnswer: "Ensure scene safety",
  },
  {
    id: uuidv4(),
    text: "The recommended compression depth in adult CPR is:",
    options: ["1-2 cm", "3-4 cm", "At least 5 cm", "More than 7 cm"],
    correctAnswer: "At least 5 cm",
  },
  {
    id: uuidv4(),
    text: "The correct compression-to-ventilation ratio for adult CPR is:",
    options: ["15:2", "30:2", "5:1", "20:2"],
    correctAnswer: "30:2",
  },
  {
    id: uuidv4(),
    text: "The primary purpose of CPR is to:",
    options: [
      "Restore consciousness",
      "Maintain circulation and oxygenation",
      "Prevent brain injury only",
      "Reduce pain",
    ],
    correctAnswer: "Maintain circulation and oxygenation",
  },
  {
    id: uuidv4(),
    text: "In adult CPR, compressions should be delivered at a rate of:",
    options: ["60-80/min", "80-100/min", "100-120/min", "140/min"],
    correctAnswer: "100-120/min",
  },
  {
    id: uuidv4(),
    text: "Which rhythm is shockable in cardiac arrest?",
    options: [
      "Asystole",
      "Pulseless electrical activity",
      "Ventricular fibrillation",
      "Sinus bradycardia",
    ],
    correctAnswer: "Ventricular fibrillation",
  },
  {
    id: uuidv4(),
    text: "AED should be used when the victim is:",
    options: [
      "Breathing normally",
      "Conscious",
      "Unresponsive and pulseless",
      "Complaining of chest pain",
    ],
    correctAnswer: "Unresponsive and pulseless",
  },
  {
    id: uuidv4(),
    text: "The most common cause of cardiac arrest in adults is:",
    options: [
      "Respiratory failure",
      "Trauma",
      "Ventricular arrhythmias",
      "Stroke",
    ],
    correctAnswer: "Ventricular arrhythmias",
  },
  {
    id: uuidv4(),
    text: "During CPR, interruptions in chest compressions should be:",
    options: [
      "Frequent",
      "Minimized",
      "At least 30 seconds",
      "Avoided completely",
    ],
    correctAnswer: "Minimized",
  },
  {
    id: uuidv4(),
    text: "The correct hand placement for adult chest compressions is:",
    options: [
      "Left side of chest",
      "Right side of chest",
      "Center of the chest on the lower half of sternum",
      "Over the ribs",
    ],
    correctAnswer: "Center of the chest on the lower half of sternum",
  },
  {
    id: uuidv4(),
    text: "When should rescue breaths be avoided?",
    options: [
      "In children",
      "If rescuer is untrained and unwilling",
      "In drowning",
      "In opioid overdose",
    ],
    correctAnswer: "If rescuer is untrained and unwilling",
  },
  {
    id: uuidv4(),
    text: "The purpose of defibrillation is to:",
    options: [
      "Restart the heart",
      "Terminate lethal arrhythmias",
      "Increase heart rate",
      "Reduce oxygen demand",
    ],
    correctAnswer: "Terminate lethal arrhythmias",
  },
  {
    id: uuidv4(),
    text: "In CPR for infants, compression depth should be about:",
    options: [
      "1 cm",
      "2 cm",
      "One-third of chest depth",
      "Half of chest depth",
    ],
    correctAnswer: "One-third of chest depth",
  },
  {
    id: uuidv4(),
    text: "Which sign confirms effective chest compressions?",
    options: [
      "Cyanosis",
      "Palpable carotid pulse during compression",
      "Apnea",
      "Hypotension",
    ],
    correctAnswer: "Palpable carotid pulse during compression",
  },
  {
    id: uuidv4(),
    text: "Oxygen during CPR should be administered at:",
    options: [
      "Low flow",
      "High concentration",
      "Intermittently",
      "Only after ROSC",
    ],
    correctAnswer: "High concentration",
  },
  {
    id: uuidv4(),
    text: "The major complication of excessive ventilation during CPR is:",
    options: ["Hypoxia", "Decreased cardiac output", "Bradycardia", "Acidosis"],
    correctAnswer: "Decreased cardiac output",
  },
  {
    id: uuidv4(),
    text: "After return of spontaneous circulation (ROSC), priority care is:",
    options: [
      "Feeding",
      "Airway and hemodynamic stabilization",
      "Mobilization",
      "Discharge planning",
    ],
    correctAnswer: "Airway and hemodynamic stabilization",
  },
  {
    id: uuidv4(),
    text: "In two-rescuer adult CPR, the second rescuer should:",
    options: [
      "Give medications",
      "Manage airway and ventilation",
      "Perform defibrillation only",
      "Monitor ECG",
    ],
    correctAnswer: "Manage airway and ventilation",
  },
  {
    id: uuidv4(),
    text: "The most important factor in successful CPR is:",
    options: [
      "Advanced airway",
      "Medications",
      "Early high-quality chest compressions",
      "Oxygen therapy",
    ],
    correctAnswer: "Early high-quality chest compressions",
  },
  {
    id: uuidv4(),
    text: "CPR may be terminated when:",
    options: [
      "Victim regains consciousness",
      "Rescuer is exhausted",
      "Advanced care takes over",
      "All of the above",
    ],
    correctAnswer: "Advanced care takes over",
  },
  {
    id: uuidv4(),
    text: "In pregnant women, CPR modifications include:",
    options: [
      "No changes",
      "Left uterine displacement",
      "Faster compressions",
      "Shallow compressions",
    ],
    correctAnswer: "Left uterine displacement",
  },
  {
    id: uuidv4(),
    text: "The drug commonly used for asystole during CPR is:",
    options: ["Amiodarone", "Atropine", "Epinephrine", "Lidocaine"],
    correctAnswer: "Epinephrine",
  },
  {
    id: uuidv4(),
    text: "Chest recoil during CPR is important because it:",
    options: [
      "Reduces pain",
      "Allows venous return",
      "Improves ventilation",
      "Prevents fractures",
    ],
    correctAnswer: "Allows venous return",
  },
  {
    id: uuidv4(),
    text: "The recommended ventilation rate with advanced airway is:",
    options: ["30/min", "15/min", "10/min", "5/min"],
    correctAnswer: "10/min",
  },
  {
    id: uuidv4(),
    text: "The most common CPR-related injury is:",
    options: [
      "Pneumothorax",
      "Rib fractures",
      "Liver rupture",
      "Spinal injury",
    ],
    correctAnswer: "Rib fractures",
  },
  {
    id: uuidv4(),
    text: "Pulse check during CPR should not exceed:",
    options: ["5 seconds", "10 seconds", "20 seconds", "30 seconds"],
    correctAnswer: "10 seconds",
  },
  {
    id: uuidv4(),
    text: "Which condition requires immediate CPR?",
    options: ["Syncope", "Sudden cardiac arrest", "Angina", "Hypotension"],
    correctAnswer: "Sudden cardiac arrest",
  },
  {
    id: uuidv4(),
    text: "The compression surface during CPR should be:",
    options: ["Soft mattress", "Firm and flat", "Pillow", "Recliner"],
    correctAnswer: "Firm and flat",
  },
  {
    id: uuidv4(),
    text: "In drowning victims, priority is given to:",
    options: [
      "Compressions first",
      "Ventilation with oxygen",
      "Defibrillation",
      "Medications",
    ],
    correctAnswer: "Ventilation with oxygen",
  },
  {
    id: uuidv4(),
    text: "CPR effectiveness is best evaluated by:",
    options: [
      "ECG alone",
      "End-tidal CO₂ monitoring",
      "Blood pressure",
      "Oxygen saturation",
    ],
    correctAnswer: "End-tidal CO₂ monitoring",
  },
  // REHABILITATION QUESTIONS 71-100
  {
    id: uuidv4(),
    text: "Rehabilitation nursing primarily focuses on:",
    options: [
      "Cure",
      "Maximizing functional independence",
      "Surgery",
      "Diagnosis",
    ],
    correctAnswer: "Maximizing functional independence",
  },
  {
    id: uuidv4(),
    text: "The key principle of rehabilitation is:",
    options: ["Bed rest", "Early mobilization", "Isolation", "Dependence"],
    correctAnswer: "Early mobilization",
  },
  {
    id: uuidv4(),
    text: "The nurse's role in rehabilitation includes:",
    options: [
      "Prescribing drugs",
      "Patient education and motivation",
      "Surgery",
      "Diagnosis",
    ],
    correctAnswer: "Patient education and motivation",
  },
  {
    id: uuidv4(),
    text: "Which patient benefits most from rehabilitation?",
    options: [
      "Acute appendicitis",
      "Stroke patient",
      "Malaria",
      "Acute diarrhea",
    ],
    correctAnswer: "Stroke patient",
  },
  {
    id: uuidv4(),
    text: "The goal of cardiac rehabilitation is to:",
    options: [
      "Cure heart disease",
      "Improve quality of life and reduce mortality",
      "Eliminate medications",
      "Prevent aging",
    ],
    correctAnswer: "Improve quality of life and reduce mortality",
  },
  {
    id: uuidv4(),
    text: "The rehabilitation team leader is often the:",
    options: ["Nurse", "Physician", "Social worker", "Psychologist"],
    correctAnswer: "Physician",
  },
  {
    id: uuidv4(),
    text: "Which phase of rehabilitation begins immediately after injury?",
    options: [
      "Community phase",
      "Acute phase",
      "Maintenance phase",
      "Vocational phase",
    ],
    correctAnswer: "Acute phase",
  },
  {
    id: uuidv4(),
    text: "Occupational therapy focuses on:",
    options: [
      "Muscle strength",
      "Activities of daily living",
      "Speech",
      "Medication use",
    ],
    correctAnswer: "Activities of daily living",
  },
  {
    id: uuidv4(),
    text: "A major goal of stroke rehabilitation is to prevent:",
    options: ["Pain", "Complications and disability", "Infection", "Fever"],
    correctAnswer: "Complications and disability",
  },
  {
    id: uuidv4(),
    text: "The use of assistive devices aims to:",
    options: [
      "Promote dependence",
      "Enhance independence",
      "Increase weakness",
      "Reduce therapy",
    ],
    correctAnswer: "Enhance independence",
  },
  {
    id: uuidv4(),
    text: "Which is a psychological aspect of rehabilitation?",
    options: [
      "Exercise",
      "Adjustment to disability",
      "Nutrition",
      "Medication",
    ],
    correctAnswer: "Adjustment to disability",
  },
  {
    id: uuidv4(),
    text: "Early rehabilitation prevents:",
    options: [
      "Healing",
      "Contractures and muscle wasting",
      "Mobility",
      "Independence",
    ],
    correctAnswer: "Contractures and muscle wasting",
  },
  {
    id: uuidv4(),
    text: "The nurse's priority in spinal cord injury rehabilitation is:",
    options: ["Feeding", "Prevention of complications", "Surgery", "Discharge"],
    correctAnswer: "Prevention of complications",
  },
  {
    id: uuidv4(),
    text: "Which condition commonly requires pulmonary rehabilitation?",
    options: [
      "Diabetes",
      "Chronic obstructive pulmonary disease",
      "Hypertension",
      "Anemia",
    ],
    correctAnswer: "Chronic obstructive pulmonary disease",
  },
  {
    id: uuidv4(),
    text: "Vocational rehabilitation focuses on:",
    options: [
      "Exercise",
      "Returning patient to employment",
      "Pain control",
      "Counseling",
    ],
    correctAnswer: "Returning patient to employment",
  },
  {
    id: uuidv4(),
    text: "Family involvement in rehabilitation is important to:",
    options: [
      "Reduce nurse workload",
      "Ensure continuity of care",
      "Replace professionals",
      "Limit patient autonomy",
    ],
    correctAnswer: "Ensure continuity of care",
  },
  {
    id: uuidv4(),
    text: "A key ethical principle in rehabilitation is:",
    options: [
      "Justice only",
      "Respect for patient autonomy",
      "Paternalism",
      "Non-participation",
    ],
    correctAnswer: "Respect for patient autonomy",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation outcomes are best measured by:",
    options: ["Diagnosis", "Functional ability", "Laboratory results", "Age"],
    correctAnswer: "Functional ability",
  },
  {
    id: uuidv4(),
    text: "Which patient is least suitable for intensive rehabilitation?",
    options: [
      "Motivated patient",
      "Unstable medical condition",
      "Supportive family",
      "Mild disability",
    ],
    correctAnswer: "Unstable medical condition",
  },
  {
    id: uuidv4(),
    text: "The nurse's teaching priority in rehabilitation is:",
    options: [
      "Disease process",
      "Self-care skills",
      "Drug names",
      "Hospital policy",
    ],
    correctAnswer: "Self-care skills",
  },
  {
    id: uuidv4(),
    text: "Community-based rehabilitation aims to:",
    options: [
      "Hospitalize patients",
      "Integrate patients into society",
      "Limit independence",
      "Reduce family role",
    ],
    correctAnswer: "Integrate patients into society",
  },
  {
    id: uuidv4(),
    text: "A major barrier to rehabilitation success is:",
    options: [
      "Team approach",
      "Poor patient motivation",
      "Early intervention",
      "Family support",
    ],
    correctAnswer: "Poor patient motivation",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation for amputees includes:",
    options: [
      "Pain control only",
      "Prosthetic training",
      "Surgery only",
      "Isolation",
    ],
    correctAnswer: "Prosthetic training",
  },
  {
    id: uuidv4(),
    text: "The nurse evaluates rehabilitation progress by assessing:",
    options: ["Diagnosis", "Achievement of goals", "Length of stay", "Cost"],
    correctAnswer: "Achievement of goals",
  },
  {
    id: uuidv4(),
    text: "Burn rehabilitation focuses on preventing:",
    options: [
      "Infection only",
      "Contractures and disfigurement",
      "Pain",
      "Shock",
    ],
    correctAnswer: "Contractures and disfigurement",
  },
  {
    id: uuidv4(),
    text: "Which professional manages speech disorders in rehabilitation?",
    options: ["Nurse", "Speech therapist", "Social worker", "Dietitian"],
    correctAnswer: "Speech therapist",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation is considered successful when the patient:",
    options: [
      "Is cured",
      "Achieves optimal independence",
      "Is discharged early",
      "Stops medication",
    ],
    correctAnswer: "Achieves optimal independence",
  },
  {
    id: uuidv4(),
    text: "Long-term rehabilitation is common in:",
    options: [
      "Acute infections",
      "Chronic neurological disorders",
      "Minor injuries",
      "Short illnesses",
    ],
    correctAnswer: "Chronic neurological disorders",
  },
  {
    id: uuidv4(),
    text: "The nurse's attitude in rehabilitation should be:",
    options: [
      "Authoritarian",
      "Encouraging and supportive",
      "Passive",
      "Detached",
    ],
    correctAnswer: "Encouraging and supportive",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation nursing is best described as:",
    options: [
      "Task-oriented care",
      "Holistic and patient-centered care",
      "Curative care",
      "Emergency care",
    ],
    correctAnswer: "Holistic and patient-centered care",
  },
  // BATCH 2: QUESTIONS 101-200
  {
    id: uuidv4(),
    text: "Which clinical sign indicates decreased cardiac output in shock?",
    options: [
      "Bounding pulse",
      "Warm skin",
      "Narrowed pulse pressure",
      "Increased urine output",
    ],
    correctAnswer: "Narrowed pulse pressure",
  },
  {
    id: uuidv4(),
    text: "Which finding is typical of late septic shock?",
    options: [
      "Warm flushed skin",
      "Bounding pulse",
      "Cold, clammy skin",
      "Hypertension",
    ],
    correctAnswer: "Cold, clammy skin",
  },
  {
    id: uuidv4(),
    text: "The primary cause of decreased preload in hypovolemic shock is:",
    options: [
      "Vasodilation",
      "Myocardial dysfunction",
      "Loss of intravascular volume",
      "Increased afterload",
    ],
    correctAnswer: "Loss of intravascular volume",
  },
  {
    id: uuidv4(),
    text: "Which assessment best differentiates cardiogenic shock from hypovolemic shock?",
    options: [
      "Blood pressure",
      "Mental status",
      "Presence of pulmonary crackles",
      "Capillary refill",
    ],
    correctAnswer: "Presence of pulmonary crackles",
  },
  {
    id: uuidv4(),
    text: "In shock, tachycardia primarily occurs to:",
    options: [
      "Reduce oxygen demand",
      "Maintain cardiac output",
      "Increase preload",
      "Reduce afterload",
    ],
    correctAnswer: "Maintain cardiac output",
  },
  {
    id: uuidv4(),
    text: "Which condition can cause obstructive shock?",
    options: [
      "Myocardial infarction",
      "Hemorrhage",
      "Cardiac tamponade",
      "Sepsis",
    ],
    correctAnswer: "Cardiac tamponade",
  },
  {
    id: uuidv4(),
    text: "A patient with septic shock is most likely to have which temperature change initially?",
    options: [
      "Hypothermia",
      "Hyperthermia",
      "Normal temperature",
      "Fluctuating temperature",
    ],
    correctAnswer: "Hyperthermia",
  },
  {
    id: uuidv4(),
    text: "Which laboratory value reflects poor oxygen delivery at the cellular level?",
    options: ["Hemoglobin", "Platelet count", "Serum lactate", "Sodium"],
    correctAnswer: "Serum lactate",
  },
  {
    id: uuidv4(),
    text: "Which nursing intervention reduces oxygen consumption in shock?",
    options: [
      "Early ambulation",
      "Providing a calm environment",
      "Encouraging oral intake",
      "Elevating temperature",
    ],
    correctAnswer: "Providing a calm environment",
  },
  {
    id: uuidv4(),
    text: "The primary pathophysiological problem in cardiogenic shock is:",
    options: [
      "Loss of vascular tone",
      "Impaired myocardial contractility",
      "Fluid loss",
      "Airway obstruction",
    ],
    correctAnswer: "Impaired myocardial contractility",
  },
  {
    id: uuidv4(),
    text: "Which shock type is associated with massive vasodilation?",
    options: [
      "Hypovolemic",
      "Cardiogenic",
      "Distributive shock",
      "Obstructive",
    ],
    correctAnswer: "Distributive shock",
  },
  {
    id: uuidv4(),
    text: "A systolic BP of 80 mmHg in shock indicates:",
    options: [
      "Compensatory stage",
      "Progressive stage",
      "Recovery stage",
      "Early stage",
    ],
    correctAnswer: "Progressive stage",
  },
  {
    id: uuidv4(),
    text: "Which parameter is most important to monitor during fluid resuscitation?",
    options: ["Temperature", "Urine output", "Bowel sounds", "Skin turgor"],
    correctAnswer: "Urine output",
  },
  {
    id: uuidv4(),
    text: "In shock, cellular hypoxia leads to:",
    options: [
      "Aerobic metabolism",
      "Anaerobic metabolism and lactic acidosis",
      "Increased ATP production",
      "Alkalosis",
    ],
    correctAnswer: "Anaerobic metabolism and lactic acidosis",
  },
  {
    id: uuidv4(),
    text: "Which patient history increases risk for cardiogenic shock?",
    options: [
      "Peptic ulcer disease",
      "Previous myocardial infarction",
      "Asthma",
      "Renal stones",
    ],
    correctAnswer: "Previous myocardial infarction",
  },
  {
    id: uuidv4(),
    text: "Which medication should be used cautiously in cardiogenic shock?",
    options: ["Inotropes", "Vasopressors", "Large-volume IV fluids", "Oxygen"],
    correctAnswer: "Large-volume IV fluids",
  },
  {
    id: uuidv4(),
    text: "The best indicator of adequate cerebral perfusion is:",
    options: [
      "Pupil size",
      "Level of consciousness",
      "Blood pressure",
      "Heart rate",
    ],
    correctAnswer: "Level of consciousness",
  },
  {
    id: uuidv4(),
    text: "Which complication is associated with prolonged hypotension in shock?",
    options: [
      "Hyperglycemia",
      "Multiple organ dysfunction syndrome (MODS)",
      "Hypertension",
      "Polyuria",
    ],
    correctAnswer: "Multiple organ dysfunction syndrome (MODS)",
  },
  {
    id: uuidv4(),
    text: "Which shock type is most associated with spinal cord injury?",
    options: ["Septic", "Hypovolemic", "Neurogenic", "Cardiogenic"],
    correctAnswer: "Neurogenic",
  },
  {
    id: uuidv4(),
    text: "Which nursing action helps prevent hypothermia in shock patients?",
    options: [
      "Cold compress",
      "Use of warm blankets",
      "Ice packs",
      "Restrict fluids",
    ],
    correctAnswer: "Use of warm blankets",
  },
  {
    id: uuidv4(),
    text: "The priority assessment in shock management is:",
    options: [
      "Nutritional status",
      "Airway, breathing, circulation",
      "Skin integrity",
      "Pain score",
    ],
    correctAnswer: "Airway, breathing, circulation",
  },
  {
    id: uuidv4(),
    text: "Which sign suggests inadequate tissue perfusion?",
    options: [
      "Pink nail beds",
      "Delayed capillary refill",
      "Normal urine output",
      "Alertness",
    ],
    correctAnswer: "Delayed capillary refill",
  },
  {
    id: uuidv4(),
    text: "A patient in shock with jugular venous distension likely has:",
    options: [
      "Hypovolemic shock",
      "Cardiogenic shock",
      "Neurogenic shock",
      "Anaphylactic shock",
    ],
    correctAnswer: "Cardiogenic shock",
  },
  {
    id: uuidv4(),
    text: "Which acid-base imbalance occurs first in early shock?",
    options: [
      "Metabolic acidosis",
      "Respiratory alkalosis",
      "Metabolic alkalosis",
      "Respiratory acidosis",
    ],
    correctAnswer: "Respiratory alkalosis",
  },
  {
    id: uuidv4(),
    text: "Which parameter best reflects oxygen delivery?",
    options: [
      "Blood pressure",
      "Cardiac output",
      "Temperature",
      "Respiratory rate",
    ],
    correctAnswer: "Cardiac output",
  },
  {
    id: uuidv4(),
    text: "Which intervention improves preload in hypovolemic shock?",
    options: [
      "Vasodilators",
      "IV fluid administration",
      "Diuretics",
      "Beta-blockers",
    ],
    correctAnswer: "IV fluid administration",
  },
  {
    id: uuidv4(),
    text: "The irreversible stage of shock is marked by:",
    options: [
      "Tachycardia only",
      "Severe cellular damage and organ failure",
      "Mild hypotension",
      "Anxiety",
    ],
    correctAnswer: "Severe cellular damage and organ failure",
  },
  {
    id: uuidv4(),
    text: "Which electrolyte imbalance worsens cardiac arrhythmias in shock?",
    options: [
      "Hyponatremia",
      "Hyperkalemia",
      "Hypocalcemia",
      "Hypermagnesemia",
    ],
    correctAnswer: "Hyperkalemia",
  },
  {
    id: uuidv4(),
    text: "In septic shock, vasodilation occurs due to:",
    options: [
      "Fluid loss",
      "Inflammatory mediators",
      "Cardiac ischemia",
      "Hypoxia alone",
    ],
    correctAnswer: "Inflammatory mediators",
  },
  {
    id: uuidv4(),
    text: "The nurse should position a shock patient supine primarily to:",
    options: [
      "Improve comfort",
      "Enhance venous return",
      "Reduce anxiety",
      "Lower BP",
    ],
    correctAnswer: "Enhance venous return",
  },
  {
    id: uuidv4(),
    text: "Which sign indicates effective fluid resuscitation?",
    options: [
      "Tachycardia",
      "Improved urine output",
      "Cold skin",
      "Hypotension",
    ],
    correctAnswer: "Improved urine output",
  },
  {
    id: uuidv4(),
    text: "Which organ failure most commonly occurs first in shock?",
    options: ["Liver", "Kidney", "Lung", "Heart"],
    correctAnswer: "Kidney",
  },
  {
    id: uuidv4(),
    text: "A decrease in mean arterial pressure below normal indicates:",
    options: [
      "Adequate perfusion",
      "Risk of organ hypoperfusion",
      "Hypervolemia",
      "Hypertension",
    ],
    correctAnswer: "Risk of organ hypoperfusion",
  },
  {
    id: uuidv4(),
    text: "Which drug improves myocardial contractility in cardiogenic shock?",
    options: ["Propranolol", "Dobutamine", "Diazepam", "Furosemide"],
    correctAnswer: "Dobutamine",
  },
  {
    id: uuidv4(),
    text: "Which clinical finding suggests recovery from shock?",
    options: [
      "Persistent acidosis",
      "Normalizing vital signs",
      "Oliguria",
      "Confusion",
    ],
    correctAnswer: "Normalizing vital signs",
  },
  {
    id: uuidv4(),
    text: "In shock, why is oxygen administered at high flow?",
    options: [
      "Reduce heart rate",
      "Maximize oxygen delivery to tissues",
      "Lower BP",
      "Prevent infection",
    ],
    correctAnswer: "Maximize oxygen delivery to tissues",
  },
  {
    id: uuidv4(),
    text: "Which assessment finding suggests worsening metabolic acidosis?",
    options: [
      "Slow breathing",
      "Deep, rapid respirations",
      "Bradycardia",
      "Normal pH",
    ],
    correctAnswer: "Deep, rapid respirations",
  },
  {
    id: uuidv4(),
    text: "Shock management requires continuous monitoring of:",
    options: ["Weight", "Hemodynamic parameters", "Vision", "Hearing"],
    correctAnswer: "Hemodynamic parameters",
  },
  {
    id: uuidv4(),
    text: "Which factor increases mortality in shock?",
    options: [
      "Early treatment",
      "Delayed recognition",
      "Adequate fluids",
      "Oxygen therapy",
    ],
    correctAnswer: "Delayed recognition",
  },
  {
    id: uuidv4(),
    text: "Shock is a medical emergency because it can lead to:",
    options: ["Pain only", "Rapid organ failure and death", "Anxiety", "Fever"],
    correctAnswer: "Rapid organ failure and death",
  },
  // CPR QUESTIONS 141-170
  {
    id: uuidv4(),
    text: "The most critical action in the first minute of cardiac arrest is:",
    options: [
      "IV access",
      "Immediate chest compressions",
      "Endotracheal intubation",
      "Medication administration",
    ],
    correctAnswer: "Immediate chest compressions",
  },
  {
    id: uuidv4(),
    text: "In adult CPR, rescue breaths should be delivered over:",
    options: ["5 seconds", "1 second", "3 seconds", "10 seconds"],
    correctAnswer: "1 second",
  },
  {
    id: uuidv4(),
    text: "Which sign confirms cardiac arrest?",
    options: [
      "Weak pulse",
      "Hypotension",
      "Unresponsiveness and absence of normal breathing",
      "Cyanosis",
    ],
    correctAnswer: "Unresponsiveness and absence of normal breathing",
  },
  {
    id: uuidv4(),
    text: "The main determinant of coronary perfusion during CPR is:",
    options: [
      "Oxygen concentration",
      "Chest compression quality",
      "Ventilation rate",
      "Drug therapy",
    ],
    correctAnswer: "Chest compression quality",
  },
  {
    id: uuidv4(),
    text: "When should defibrillation be attempted?",
    options: [
      "Immediately for all arrests",
      "When a shockable rhythm is identified",
      "After 10 minutes of CPR",
      "Only after drug therapy",
    ],
    correctAnswer: "When a shockable rhythm is identified",
  },
  {
    id: uuidv4(),
    text: "Which rhythm requires CPR but not defibrillation?",
    options: [
      "Ventricular fibrillation",
      "Asystole",
      "Ventricular tachycardia",
      "Torsades de pointes",
    ],
    correctAnswer: "Asystole",
  },
  {
    id: uuidv4(),
    text: "The AED analyzes heart rhythm to determine:",
    options: ["Heart rate", "Need for shock", "Blood pressure", "Oxygen level"],
    correctAnswer: "Need for shock",
  },
  {
    id: uuidv4(),
    text: "During CPR, compression depth should be avoided if it causes:",
    options: ["Rib fracture", "Insufficient chest recoil", "Pain", "Bruising"],
    correctAnswer: "Insufficient chest recoil",
  },
  {
    id: uuidv4(),
    text: "Which factor most affects survival after cardiac arrest?",
    options: ["Age", "Time to first defibrillation", "Gender", "Body weight"],
    correctAnswer: "Time to first defibrillation",
  },
  {
    id: uuidv4(),
    text: "Which action should be avoided during CPR?",
    options: [
      "Switching compressors",
      "Leaning on the chest between compressions",
      "Using AED",
      "Giving oxygen",
    ],
    correctAnswer: "Leaning on the chest between compressions",
  },
  {
    id: uuidv4(),
    text: "In infant CPR, the preferred technique for single rescuer is:",
    options: [
      "Two-thumb technique",
      "Two-finger technique",
      "Heel of hand",
      "Fist",
    ],
    correctAnswer: "Two-finger technique",
  },
  {
    id: uuidv4(),
    text: "Which drug is indicated for refractory ventricular fibrillation?",
    options: ["Atropine", "Amiodarone", "Adenosine", "Dopamine"],
    correctAnswer: "Amiodarone",
  },
  {
    id: uuidv4(),
    text: "After ROSC, oxygen saturation should be maintained at:",
    options: ["80-85%", "85-90%", "94-98%", "100%"],
    correctAnswer: "94-98%",
  },
  {
    id: uuidv4(),
    text: "The primary cause of ineffective CPR is:",
    options: [
      "Lack of drugs",
      "Poor compression technique",
      "No AED",
      "Delayed intubation",
    ],
    correctAnswer: "Poor compression technique",
  },
  {
    id: uuidv4(),
    text: "Which patient population has highest CPR success rate?",
    options: [
      "Elderly",
      "Witnessed arrest with early CPR",
      "Chronic illness",
      "Prolonged arrest",
    ],
    correctAnswer: "Witnessed arrest with early CPR",
  },
  {
    id: uuidv4(),
    text: "CPR in trauma patients prioritizes:",
    options: [
      "Defibrillation",
      "Airway control and bleeding management",
      "Medications",
      "Monitoring",
    ],
    correctAnswer: "Airway control and bleeding management",
  },
  {
    id: uuidv4(),
    text: "Which sign indicates adequate ventilation during CPR?",
    options: [
      "Cyanosis",
      "Visible chest rise",
      "Abdominal distension",
      "Hyperventilation",
    ],
    correctAnswer: "Visible chest rise",
  },
  {
    id: uuidv4(),
    text: "The goal of post-cardiac arrest care is to:",
    options: [
      "Discharge early",
      "Prevent secondary brain injury",
      "Stop medications",
      "Reduce cost",
    ],
    correctAnswer: "Prevent secondary brain injury",
  },
  {
    id: uuidv4(),
    text: "CPR should continue until:",
    options: [
      "Family arrives",
      "ROSC or termination of efforts",
      "AED battery dies",
      "30 minutes pass",
    ],
    correctAnswer: "ROSC or termination of efforts",
  },
  {
    id: uuidv4(),
    text: "In opioid overdose causing arrest, which drug is useful?",
    options: ["Diazepam", "Naloxone", "Epinephrine", "Lidocaine"],
    correctAnswer: "Naloxone",
  },
  {
    id: uuidv4(),
    text: "Which factor decreases CPR effectiveness?",
    options: [
      "Firm surface",
      "Frequent pauses in compressions",
      "Proper depth",
      "Early defibrillation",
    ],
    correctAnswer: "Frequent pauses in compressions",
  },
  {
    id: uuidv4(),
    text: "The most common error during CPR is:",
    options: [
      "Excessive compressions",
      "Inadequate compression depth",
      "Early defibrillation",
      "Early airway",
    ],
    correctAnswer: "Inadequate compression depth",
  },
  {
    id: uuidv4(),
    text: "The role of the team leader during CPR is to:",
    options: [
      "Perform compressions",
      "Coordinate and direct resuscitation efforts",
      "Ventilate patient",
      "Administer oxygen only",
    ],
    correctAnswer: "Coordinate and direct resuscitation efforts",
  },
  {
    id: uuidv4(),
    text: "CPR training emphasizes:",
    options: [
      "Theory only",
      "Hands-on practice",
      "Medication use",
      "ECG reading",
    ],
    correctAnswer: "Hands-on practice",
  },
  {
    id: uuidv4(),
    text: "The best predictor of neurological outcome after CPR is:",
    options: ["Blood pressure", "Duration of cardiac arrest", "Age", "Gender"],
    correctAnswer: "Duration of cardiac arrest",
  },
  {
    id: uuidv4(),
    text: "Which intervention improves venous return during CPR?",
    options: [
      "Upright position",
      "Proper chest recoil",
      "Hyperventilation",
      "Sedation",
    ],
    correctAnswer: "Proper chest recoil",
  },
  {
    id: uuidv4(),
    text: "CPR quality is improved by rotating compressors every:",
    options: ["5 minutes", "2 minutes", "10 minutes", "30 seconds"],
    correctAnswer: "2 minutes",
  },
  {
    id: uuidv4(),
    text: "Which rhythm indicates successful defibrillation?",
    options: [
      "Asystole",
      "Ventricular fibrillation",
      "Organized rhythm with pulse",
      "Pulseless VT",
    ],
    correctAnswer: "Organized rhythm with pulse",
  },
  {
    id: uuidv4(),
    text: "The primary goal of ventilation during CPR is to:",
    options: [
      "Normalize CO₂",
      "Provide oxygen to vital organs",
      "Reduce BP",
      "Prevent rib fractures",
    ],
    correctAnswer: "Provide oxygen to vital organs",
  },
  {
    id: uuidv4(),
    text: "Which action is appropriate immediately after AED shock?",
    options: [
      "Check pulse",
      "Resume chest compressions",
      "Give breaths",
      "Stop CPR",
    ],
    correctAnswer: "Resume chest compressions",
  },
  // REHABILITATION QUESTIONS 171-200
  {
    id: uuidv4(),
    text: "Rehabilitation nursing emphasizes:",
    options: [
      "Cure of disease",
      "Adaptation to functional limitations",
      "Acute care",
      "Emergency care",
    ],
    correctAnswer: "Adaptation to functional limitations",
  },
  {
    id: uuidv4(),
    text: "The main aim of neurological rehabilitation is to:",
    options: [
      "Eliminate disease",
      "Promote neuroplasticity and function",
      "Prevent infection",
      "Reduce pain only",
    ],
    correctAnswer: "Promote neuroplasticity and function",
  },
  {
    id: uuidv4(),
    text: "Which patient is a candidate for early rehabilitation?",
    options: [
      "Hemodynamically unstable",
      "Medically stable post-stroke patient",
      "Unconscious patient",
      "Terminally ill patient",
    ],
    correctAnswer: "Medically stable post-stroke patient",
  },
  {
    id: uuidv4(),
    text: "The nurse promotes independence by:",
    options: [
      "Doing tasks for patient",
      "Encouraging self-care activities",
      "Restricting movement",
      "Limiting education",
    ],
    correctAnswer: "Encouraging self-care activities",
  },
  {
    id: uuidv4(),
    text: "Which rehabilitation goal is realistic for a paraplegic patient?",
    options: [
      "Walking independently",
      "Wheelchair mobility and self-care",
      "Complete recovery",
      "No assistive devices",
    ],
    correctAnswer: "Wheelchair mobility and self-care",
  },
  {
    id: uuidv4(),
    text: "The most important factor influencing rehabilitation outcome is:",
    options: ["Age", "Patient motivation", "Gender", "Diagnosis"],
    correctAnswer: "Patient motivation",
  },
  {
    id: uuidv4(),
    text: "Which complication should be prevented during prolonged immobility?",
    options: ["Hypertension", "Pressure ulcers", "Hyperglycemia", "Fever"],
    correctAnswer: "Pressure ulcers",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation after myocardial infarction includes:",
    options: [
      "Bed rest only",
      "Gradual exercise training",
      "No education",
      "Isolation",
    ],
    correctAnswer: "Gradual exercise training",
  },
  {
    id: uuidv4(),
    text: "The nurse's role in discharge planning is to:",
    options: [
      "Decide alone",
      "Coordinate continued care and resources",
      "End care",
      "Avoid family involvement",
    ],
    correctAnswer: "Coordinate continued care and resources",
  },
  {
    id: uuidv4(),
    text: "Which is a social goal of rehabilitation?",
    options: [
      "Muscle strength",
      "Community reintegration",
      "Pain control",
      "Wound healing",
    ],
    correctAnswer: "Community reintegration",
  },
  {
    id: uuidv4(),
    text: "The use of splints in rehabilitation helps to:",
    options: [
      "Cause stiffness",
      "Prevent deformities",
      "Increase pain",
      "Reduce circulation",
    ],
    correctAnswer: "Prevent deformities",
  },
  {
    id: uuidv4(),
    text: "A major focus of geriatric rehabilitation is:",
    options: [
      "Aggressive surgery",
      "Maintaining functional independence",
      "Cure of disease",
      "Bed rest",
    ],
    correctAnswer: "Maintaining functional independence",
  },
  {
    id: uuidv4(),
    text: "Which therapy improves balance and coordination?",
    options: [
      "Speech therapy",
      "Physical therapy",
      "Occupational therapy",
      "Nutrition therapy",
    ],
    correctAnswer: "Physical therapy",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation goals should be:",
    options: [
      "Nurse-centered",
      "Patient-centered and realistic",
      "Rigid",
      "Short-term only",
    ],
    correctAnswer: "Patient-centered and realistic",
  },
  {
    id: uuidv4(),
    text: "Which patient benefit results from effective rehabilitation?",
    options: [
      "Increased dependence",
      "Improved quality of life",
      "Longer hospitalization",
      "Reduced mobility",
    ],
    correctAnswer: "Improved quality of life",
  },
  {
    id: uuidv4(),
    text: "Family education in rehabilitation helps to:",
    options: [
      "Replace professionals",
      "Support long-term care at home",
      "Increase dependence",
      "Limit autonomy",
    ],
    correctAnswer: "Support long-term care at home",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation nursing care plans are based on:",
    options: ["Diagnosis alone", "Functional assessment", "Age", "Gender"],
    correctAnswer: "Functional assessment",
  },
  {
    id: uuidv4(),
    text: "Which condition commonly requires long-term rehabilitation?",
    options: [
      "Acute gastritis",
      "Spinal cord injury",
      "Malaria",
      "Tonsillitis",
    ],
    correctAnswer: "Spinal cord injury",
  },
  {
    id: uuidv4(),
    text: "The nurse evaluates rehabilitation success by:",
    options: [
      "Length of stay",
      "Achievement of functional goals",
      "Cost of care",
      "Medication use",
    ],
    correctAnswer: "Achievement of functional goals",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation programs should be:",
    options: [
      "Uniform for all",
      "Individualized",
      "Diagnosis-based only",
      "Short-term",
    ],
    correctAnswer: "Individualized",
  },
  {
    id: uuidv4(),
    text: "Which ethical issue commonly arises in rehabilitation?",
    options: [
      "Consent refusal",
      "Balancing independence and safety",
      "Resource waste",
      "Medication error",
    ],
    correctAnswer: "Balancing independence and safety",
  },
  {
    id: uuidv4(),
    text: "The nurse encourages adherence to rehabilitation by:",
    options: ["Punishment", "Positive reinforcement", "Isolation", "Threats"],
    correctAnswer: "Positive reinforcement",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation begins:",
    options: [
      "At discharge",
      "As soon as patient is medically stable",
      "After full recovery",
      "At home only",
    ],
    correctAnswer: "As soon as patient is medically stable",
  },
  {
    id: uuidv4(),
    text: "Which assistive device improves mobility in lower-limb weakness?",
    options: ["Hearing aid", "Walker", "Splint", "Brace for hand"],
    correctAnswer: "Walker",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation after brain injury focuses on:",
    options: [
      "Rest only",
      "Cognitive and functional recovery",
      "Medication only",
      "Isolation",
    ],
    correctAnswer: "Cognitive and functional recovery",
  },
  {
    id: uuidv4(),
    text: "A multidisciplinary approach in rehabilitation ensures:",
    options: [
      "Delayed care",
      "Comprehensive patient management",
      "Increased cost only",
      "Duplication of care",
    ],
    correctAnswer: "Comprehensive patient management",
  },
  {
    id: uuidv4(),
    text: "Which outcome reflects successful vocational rehabilitation?",
    options: [
      "Improved muscle tone",
      "Return to gainful employment",
      "Reduced pain",
      "Better nutrition",
    ],
    correctAnswer: "Return to gainful employment",
  },
  {
    id: uuidv4(),
    text: "The nurse supports coping in rehabilitation by:",
    options: [
      "Ignoring emotions",
      "Providing emotional support",
      "Limiting interaction",
      "Discouraging expression",
    ],
    correctAnswer: "Providing emotional support",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation nursing is continuous because:",
    options: [
      "Patients never recover",
      "Needs change over time",
      "It is costly",
      "It replaces acute care",
    ],
    correctAnswer: "Needs change over time",
  },
  {
    id: uuidv4(),
    text: "The ultimate goal of rehabilitation is to:",
    options: [
      "Cure disease",
      "Maximize independence and quality of life",
      "Reduce hospital stay",
      "Eliminate disability",
    ],
    correctAnswer: "Maximize independence and quality of life",
  },
  // BATCH 3: QUESTIONS 201-300
  {
    id: uuidv4(),
    text: "Which assessment finding suggests decreased preload?",
    options: [
      "Jugular venous distension",
      "Pulmonary crackles",
      "Flat neck veins",
      "Bounding pulse",
    ],
    correctAnswer: "Flat neck veins",
  },
  {
    id: uuidv4(),
    text: "The primary reason for administering vasopressors in shock is to:",
    options: [
      "Increase urine output",
      "Maintain adequate mean arterial pressure",
      "Reduce heart rate",
      "Improve ventilation",
    ],
    correctAnswer: "Maintain adequate mean arterial pressure",
  },
  {
    id: uuidv4(),
    text: "Which sign indicates compensatory shock?",
    options: [
      "Severe hypotension",
      "Tachycardia with normal BP",
      "Multi-organ failure",
      "Bradycardia",
    ],
    correctAnswer: "Tachycardia with normal BP",
  },
  {
    id: uuidv4(),
    text: "In shock, decreased capillary perfusion leads to:",
    options: [
      "Warm extremities",
      "Cool, mottled skin",
      "Increased sweating",
      "Edema",
    ],
    correctAnswer: "Cool, mottled skin",
  },
  {
    id: uuidv4(),
    text: "Which parameter best reflects left ventricular function?",
    options: ["CVP", "Cardiac output", "Urine output", "Temperature"],
    correctAnswer: "Cardiac output",
  },
  {
    id: uuidv4(),
    text: "The most common cause of distributive shock worldwide is:",
    options: ["Anaphylaxis", "Neurogenic shock", "Sepsis", "Burns"],
    correctAnswer: "Sepsis",
  },
  {
    id: uuidv4(),
    text: "Which medication reduces afterload in cardiogenic shock?",
    options: ["Norepinephrine", "Nitroglycerin", "Dopamine", "Epinephrine"],
    correctAnswer: "Nitroglycerin",
  },
  {
    id: uuidv4(),
    text: "A patient in shock has Kussmaul respirations due to:",
    options: [
      "Respiratory alkalosis",
      "Metabolic acidosis",
      "Pulmonary edema",
      "Hypoxia alone",
    ],
    correctAnswer: "Metabolic acidosis",
  },
  {
    id: uuidv4(),
    text: "Which assessment finding suggests worsening hypovolemic shock?",
    options: [
      "Increasing BP",
      "Decreasing urine output",
      "Warm skin",
      "Decreased heart rate",
    ],
    correctAnswer: "Decreasing urine output",
  },
  {
    id: uuidv4(),
    text: "The primary reason for inserting a urinary catheter in shock is to:",
    options: [
      "Relieve retention",
      "Monitor urine output accurately",
      "Prevent infection",
      "Reduce discomfort",
    ],
    correctAnswer: "Monitor urine output accurately",
  },
  {
    id: uuidv4(),
    text: "Which shock type presents with hypotension and bradycardia?",
    options: ["Hypovolemic", "Cardiogenic", "Neurogenic", "Septic"],
    correctAnswer: "Neurogenic",
  },
  {
    id: uuidv4(),
    text: "In septic shock, capillary leakage causes:",
    options: [
      "Increased preload",
      "Relative hypovolemia",
      "Hypertension",
      "Bradycardia",
    ],
    correctAnswer: "Relative hypovolemia",
  },
  {
    id: uuidv4(),
    text: "Which indicator suggests inadequate oxygen delivery?",
    options: [
      "Normal ABG",
      "Elevated serum lactate",
      "Normal urine output",
      "Warm skin",
    ],
    correctAnswer: "Elevated serum lactate",
  },
  {
    id: uuidv4(),
    text: "The most effective way to prevent shock-related complications is:",
    options: [
      "Sedation",
      "Early recognition and intervention",
      "Fluid restriction",
      "Bed rest",
    ],
    correctAnswer: "Early recognition and intervention",
  },
  {
    id: uuidv4(),
    text: "Which hemodynamic change occurs first in hypovolemic shock?",
    options: [
      "Hypotension",
      "Decreased venous return",
      "Bradycardia",
      "Pulmonary edema",
    ],
    correctAnswer: "Decreased venous return",
  },
  {
    id: uuidv4(),
    text: "Which lab value indicates hemoconcentration in hypovolemia?",
    options: [
      "Decreased hematocrit",
      "Increased hematocrit",
      "Decreased hemoglobin",
      "Increased platelets only",
    ],
    correctAnswer: "Increased hematocrit",
  },
  {
    id: uuidv4(),
    text: "Shock-induced kidney injury primarily results from:",
    options: [
      "Infection",
      "Prolonged renal hypoperfusion",
      "Drug toxicity",
      "Obstruction",
    ],
    correctAnswer: "Prolonged renal hypoperfusion",
  },
  {
    id: uuidv4(),
    text: "Which assessment finding differentiates septic shock from cardiogenic shock?",
    options: [
      "Hypotension",
      "Low systemic vascular resistance",
      "Tachycardia",
      "Decreased urine output",
    ],
    correctAnswer: "Low systemic vascular resistance",
  },
  {
    id: uuidv4(),
    text: "Which nursing intervention reduces preload?",
    options: [
      "IV fluids",
      "Upright positioning",
      "Leg elevation",
      "Blood transfusion",
    ],
    correctAnswer: "Upright positioning",
  },
  {
    id: uuidv4(),
    text: "The most reliable sign of effective vasopressor therapy is:",
    options: [
      "Increased HR",
      "Improved mean arterial pressure",
      "Warm skin",
      "Reduced anxiety",
    ],
    correctAnswer: "Improved mean arterial pressure",
  },
  {
    id: uuidv4(),
    text: "Which complication is associated with massive transfusion in shock?",
    options: ["Hypercalcemia", "Hypocalcemia", "Hyperkalemia", "Hypernatremia"],
    correctAnswer: "Hypocalcemia",
  },
  {
    id: uuidv4(),
    text: "Which assessment finding suggests early organ dysfunction?",
    options: [
      "Normal mentation",
      "Subtle confusion",
      "Normal urine output",
      "Stable vitals",
    ],
    correctAnswer: "Subtle confusion",
  },
  {
    id: uuidv4(),
    text: "Which type of shock benefits most from rapid fluid boluses?",
    options: ["Cardiogenic", "Hypovolemic", "Obstructive", "Neurogenic"],
    correctAnswer: "Hypovolemic",
  },
  {
    id: uuidv4(),
    text: "The goal of lactate-guided therapy in shock is to:",
    options: [
      "Increase BP",
      "Improve tissue perfusion",
      "Reduce fever",
      "Control pain",
    ],
    correctAnswer: "Improve tissue perfusion",
  },
  {
    id: uuidv4(),
    text: "Which sign suggests impending cardiovascular collapse?",
    options: [
      "Anxiety",
      "Falling BP despite treatment",
      "Tachycardia",
      "Pale skin",
    ],
    correctAnswer: "Falling BP despite treatment",
  },
  {
    id: uuidv4(),
    text: "Which electrolyte abnormality commonly accompanies acidosis in shock?",
    options: ["Hypokalemia", "Hyperkalemia", "Hypercalcemia", "Hypomagnesemia"],
    correctAnswer: "Hyperkalemia",
  },
  {
    id: uuidv4(),
    text: "Which hemodynamic parameter reflects preload?",
    options: ["MAP", "Central venous pressure", "Cardiac index", "SVR"],
    correctAnswer: "Central venous pressure",
  },
  {
    id: uuidv4(),
    text: "Which nursing action is priority during rapid fluid resuscitation?",
    options: [
      "Oral intake",
      "Monitor for signs of fluid overload",
      "Restrict oxygen",
      "Encourage ambulation",
    ],
    correctAnswer: "Monitor for signs of fluid overload",
  },
  {
    id: uuidv4(),
    text: "In cardiogenic shock, pulmonary congestion occurs due to:",
    options: [
      "Vasodilation",
      "Left ventricular failure",
      "Hypovolemia",
      "Infection",
    ],
    correctAnswer: "Left ventricular failure",
  },
  {
    id: uuidv4(),
    text: "Which assessment finding indicates improvement in shock?",
    options: [
      "Persistent tachycardia",
      "Increasing urine output",
      "Confusion",
      "Metabolic acidosis",
    ],
    correctAnswer: "Increasing urine output",
  },
  {
    id: uuidv4(),
    text: "Which shock stage shows irreversible cellular damage?",
    options: ["Compensatory", "Progressive", "Irreversible", "Recovery"],
    correctAnswer: "Irreversible",
  },
  {
    id: uuidv4(),
    text: "Which laboratory marker reflects inflammatory response in sepsis?",
    options: ["Hemoglobin", "Procalcitonin", "Sodium", "Creatinine"],
    correctAnswer: "Procalcitonin",
  },
  {
    id: uuidv4(),
    text: "The primary purpose of invasive hemodynamic monitoring is to:",
    options: [
      "Reduce workload",
      "Guide therapy accurately",
      "Diagnose infection",
      "Provide comfort",
    ],
    correctAnswer: "Guide therapy accurately",
  },
  {
    id: uuidv4(),
    text: "Which factor increases risk of hypovolemic shock postoperatively?",
    options: [
      "Early feeding",
      "Uncontrolled bleeding",
      "Pain control",
      "Early ambulation",
    ],
    correctAnswer: "Uncontrolled bleeding",
  },
  {
    id: uuidv4(),
    text: "Which nursing diagnosis is most appropriate in early shock?",
    options: [
      "Fluid volume excess",
      "Risk for ineffective tissue perfusion",
      "Impaired skin integrity",
      "Chronic pain",
    ],
    correctAnswer: "Risk for ineffective tissue perfusion",
  },
  {
    id: uuidv4(),
    text: "In septic shock, fluids are administered primarily to:",
    options: [
      "Reduce fever",
      "Increase intravascular volume",
      "Treat infection",
      "Decrease HR",
    ],
    correctAnswer: "Increase intravascular volume",
  },
  {
    id: uuidv4(),
    text: "Which assessment finding suggests vasodilation?",
    options: [
      "Narrow pulse pressure",
      "Wide pulse pressure",
      "Cold skin",
      "Bradycardia",
    ],
    correctAnswer: "Wide pulse pressure",
  },
  {
    id: uuidv4(),
    text: "The most common cause of death in shock is:",
    options: [
      "Arrhythmia",
      "Multiple organ failure",
      "Infection",
      "Hypoglycemia",
    ],
    correctAnswer: "Multiple organ failure",
  },
  {
    id: uuidv4(),
    text: "Which intervention improves oxygen delivery most rapidly?",
    options: ["Antibiotics", "High-flow oxygen", "Diuretics", "Sedatives"],
    correctAnswer: "High-flow oxygen",
  },
  {
    id: uuidv4(),
    text: "Which condition is least likely to cause shock?",
    options: [
      "Severe burns",
      "Massive hemorrhage",
      "Mild dehydration",
      "Sepsis",
    ],
    correctAnswer: "Mild dehydration",
  },
  // CPR QUESTIONS 241-270
  {
    id: uuidv4(),
    text: "Which action should occur first when finding an unresponsive adult?",
    options: [
      "Call family",
      "Check responsiveness and breathing",
      "Start rescue breaths",
      "Get AED",
    ],
    correctAnswer: "Check responsiveness and breathing",
  },
  {
    id: uuidv4(),
    text: "The most important component of high-quality CPR is:",
    options: [
      "Advanced airway",
      "Effective chest compressions",
      "IV access",
      "Drug therapy",
    ],
    correctAnswer: "Effective chest compressions",
  },
  {
    id: uuidv4(),
    text: "In CPR, compression fraction should be:",
    options: ["Less than 40%", "50%", "At least 60%", "90%"],
    correctAnswer: "At least 60%",
  },
  {
    id: uuidv4(),
    text: "Which factor determines AED shock advice?",
    options: [
      "Patient age",
      "Cardiac rhythm",
      "Blood pressure",
      "Oxygen saturation",
    ],
    correctAnswer: "Cardiac rhythm",
  },
  {
    id: uuidv4(),
    text: "Which drug improves coronary perfusion pressure during CPR?",
    options: ["Amiodarone", "Epinephrine", "Atropine", "Lidocaine"],
    correctAnswer: "Epinephrine",
  },
  {
    id: uuidv4(),
    text: "Excessive ventilation during CPR causes:",
    options: [
      "Hypoxia",
      "Decreased venous return",
      "Bradycardia",
      "Hypothermia",
    ],
    correctAnswer: "Decreased venous return",
  },
  {
    id: uuidv4(),
    text: "Which pulse is preferred for adult CPR assessment?",
    options: ["Radial", "Femoral", "Carotid", "Brachial"],
    correctAnswer: "Carotid",
  },
  {
    id: uuidv4(),
    text: "The main purpose of chest compressions is to:",
    options: [
      "Oxygenate lungs",
      "Circulate blood to vital organs",
      "Restore rhythm",
      "Reduce acidosis",
    ],
    correctAnswer: "Circulate blood to vital organs",
  },
  {
    id: uuidv4(),
    text: "In child CPR, the compression-to-ventilation ratio for single rescuer is:",
    options: ["15:2", "30:2", "5:1", "20:2"],
    correctAnswer: "30:2",
  },
  {
    id: uuidv4(),
    text: "Which sign indicates ineffective CPR?",
    options: [
      "ETCO₂ > 10 mmHg",
      "No chest recoil",
      "Palpable pulse",
      "Chest rise",
    ],
    correctAnswer: "No chest recoil",
  },
  {
    id: uuidv4(),
    text: "CPR should be performed on a surface that is:",
    options: ["Soft", "Firm and flat", "Elevated", "Cushioned"],
    correctAnswer: "Firm and flat",
  },
  {
    id: uuidv4(),
    text: "Which rhythm responds best to defibrillation?",
    options: [
      "Asystole",
      "PEA",
      "Ventricular fibrillation",
      "Sinus tachycardia",
    ],
    correctAnswer: "Ventricular fibrillation",
  },
  {
    id: uuidv4(),
    text: "During CPR, rescuers should switch roles to prevent fatigue every:",
    options: ["1 minute", "2 minutes", "5 minutes", "10 minutes"],
    correctAnswer: "2 minutes",
  },
  {
    id: uuidv4(),
    text: "The best indicator of ROSC is:",
    options: [
      "Improved color",
      "Palpable pulse and BP",
      "Normal ECG",
      "Increased RR",
    ],
    correctAnswer: "Palpable pulse and BP",
  },
  {
    id: uuidv4(),
    text: "CPR in hypothermic cardiac arrest should continue until:",
    options: [
      "AED available",
      "Patient is rewarmed",
      "20 minutes pass",
      "Drugs administered",
    ],
    correctAnswer: "Patient is rewarmed",
  },
  {
    id: uuidv4(),
    text: "Which intervention prevents aspiration during CPR?",
    options: [
      "Supine position",
      "Airway protection",
      "Hyperventilation",
      "Suction only",
    ],
    correctAnswer: "Airway protection",
  },
  {
    id: uuidv4(),
    text: "The major goal of post-resuscitation care is to:",
    options: [
      "Normalize HR",
      "Optimize neurologic recovery",
      "Reduce cost",
      "Discontinue oxygen",
    ],
    correctAnswer: "Optimize neurologic recovery",
  },
  {
    id: uuidv4(),
    text: "Which monitoring confirms CPR quality?",
    options: ["ECG", "End-tidal CO₂", "Pulse oximetry", "BP cuff"],
    correctAnswer: "End-tidal CO₂",
  },
  {
    id: uuidv4(),
    text: "CPR should be stopped when:",
    options: [
      "AED arrives",
      "ROSC occurs",
      "Rescuer tires briefly",
      "Drugs exhausted",
    ],
    correctAnswer: "ROSC occurs",
  },
  {
    id: uuidv4(),
    text: "Which factor improves CPR outcomes in hospitals?",
    options: [
      "Delayed response",
      "Rapid response teams",
      "Fewer staff",
      "Less monitoring",
    ],
    correctAnswer: "Rapid response teams",
  },
  {
    id: uuidv4(),
    text: "The recommended airway device during basic CPR is:",
    options: [
      "Endotracheal tube",
      "Bag-valve-mask",
      "Laryngeal mask",
      "Tracheostomy",
    ],
    correctAnswer: "Bag-valve-mask",
  },
  {
    id: uuidv4(),
    text: "Which condition may require prolonged CPR?",
    options: ["MI", "Hypothermia", "Stroke", "Sepsis"],
    correctAnswer: "Hypothermia",
  },
  {
    id: uuidv4(),
    text: "CPR complications include all EXCEPT:",
    options: [
      "Rib fractures",
      "Hypertension",
      "Pneumothorax",
      "Internal injuries",
    ],
    correctAnswer: "Hypertension",
  },
  {
    id: uuidv4(),
    text: "Which patient has the lowest CPR success rate?",
    options: [
      "Witnessed arrest",
      "Prolonged unwitnessed arrest",
      "Early CPR",
      "Shockable rhythm",
    ],
    correctAnswer: "Prolonged unwitnessed arrest",
  },
  {
    id: uuidv4(),
    text: "After defibrillation, what is the immediate next action?",
    options: [
      "Check pulse",
      "Resume chest compressions",
      "Ventilate",
      "Analyze rhythm",
    ],
    correctAnswer: "Resume chest compressions",
  },
  {
    id: uuidv4(),
    text: "Which oxygen device is preferred during CPR?",
    options: [
      "Nasal cannula",
      "Bag-valve-mask with oxygen",
      "Simple mask",
      "Venturi mask",
    ],
    correctAnswer: "Bag-valve-mask with oxygen",
  },
  {
    id: uuidv4(),
    text: "Which drug treats torsades de pointes during CPR?",
    options: ["Epinephrine", "Magnesium sulfate", "Atropine", "Adenosine"],
    correctAnswer: "Magnesium sulfate",
  },
  {
    id: uuidv4(),
    text: "Which action improves cerebral perfusion during CPR?",
    options: [
      "Hyperventilation",
      "Adequate compression depth",
      "Shallow breaths",
      "Upright position",
    ],
    correctAnswer: "Adequate compression depth",
  },
  {
    id: uuidv4(),
    text: "The CPR compression depth for children is:",
    options: [
      "1 cm",
      "At least one-third of chest depth",
      "Half of chest depth",
      "Same as adult",
    ],
    correctAnswer: "At least one-third of chest depth",
  },
  {
    id: uuidv4(),
    text: "Which factor most reduces survival in cardiac arrest?",
    options: ["Age", "Delayed CPR initiation", "Weight", "Gender"],
    correctAnswer: "Delayed CPR initiation",
  },
  // REHABILITATION QUESTIONS 271-300
  {
    id: uuidv4(),
    text: "The primary focus of rehabilitation nursing is to:",
    options: [
      "Cure illness",
      "Promote functional independence",
      "Manage acute symptoms",
      "Prevent admission",
    ],
    correctAnswer: "Promote functional independence",
  },
  {
    id: uuidv4(),
    text: "Which assessment tool measures functional ability?",
    options: [
      "Glasgow Coma Scale",
      "Barthel Index",
      "APGAR score",
      "Braden scale",
    ],
    correctAnswer: "Barthel Index",
  },
  {
    id: uuidv4(),
    text: "Early mobilization in rehabilitation helps prevent:",
    options: ["Healing", "Muscle atrophy", "Independence", "Motivation"],
    correctAnswer: "Muscle atrophy",
  },
  {
    id: uuidv4(),
    text: "Which patient requires comprehensive rehabilitation?",
    options: [
      "Mild flu",
      "Traumatic brain injury",
      "Acute gastritis",
      "Simple fracture",
    ],
    correctAnswer: "Traumatic brain injury",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation goals should be set:",
    options: [
      "By nurse only",
      "With patient and family involvement",
      "By physician alone",
      "Without patient input",
    ],
    correctAnswer: "With patient and family involvement",
  },
  {
    id: uuidv4(),
    text: "Which professional focuses on cognitive retraining?",
    options: ["Nurse", "Neuropsychologist", "Dietitian", "Pharmacist"],
    correctAnswer: "Neuropsychologist",
  },
  {
    id: uuidv4(),
    text: "A major risk during prolonged immobility is:",
    options: ["Hypertension", "Deep vein thrombosis", "Hyperglycemia", "Fever"],
    correctAnswer: "Deep vein thrombosis",
  },
  {
    id: uuidv4(),
    text: "Cardiac rehabilitation phase I occurs:",
    options: ["At home", "In hospital", "At workplace", "In community"],
    correctAnswer: "In hospital",
  },
  {
    id: uuidv4(),
    text: "Which intervention improves self-esteem in rehabilitation patients?",
    options: [
      "Isolation",
      "Positive feedback",
      "Task completion by nurse",
      "Restriction",
    ],
    correctAnswer: "Positive feedback",
  },
  {
    id: uuidv4(),
    text: "The nurse encourages adherence to rehab by:",
    options: ["Punishment", "Goal setting", "Ignoring refusal", "Threats"],
    correctAnswer: "Goal setting",
  },
  {
    id: uuidv4(),
    text: "Which condition commonly needs vocational rehabilitation?",
    options: [
      "Acute infection",
      "Spinal cord injury",
      "Appendicitis",
      "Malaria",
    ],
    correctAnswer: "Spinal cord injury",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation for amputees should begin:",
    options: [
      "After wound healing",
      "As soon as medically stable",
      "At discharge",
      "After prosthesis fitting",
    ],
    correctAnswer: "As soon as medically stable",
  },
  {
    id: uuidv4(),
    text: "Which therapy improves fine motor skills?",
    options: [
      "Physical therapy",
      "Occupational therapy",
      "Speech therapy",
      "Respiratory therapy",
    ],
    correctAnswer: "Occupational therapy",
  },
  {
    id: uuidv4(),
    text: "Family education in rehab focuses on:",
    options: [
      "Replacing nurses",
      "Supporting patient independence",
      "Limiting activity",
      "Enforcing rest",
    ],
    correctAnswer: "Supporting patient independence",
  },
  {
    id: uuidv4(),
    text: "The nurse evaluates rehab effectiveness by assessing:",
    options: [
      "Length of stay",
      "Achievement of functional goals",
      "Cost of care",
      "Diagnosis",
    ],
    correctAnswer: "Achievement of functional goals",
  },
  {
    id: uuidv4(),
    text: "Community-based rehabilitation aims to:",
    options: [
      "Hospitalize patients",
      "Use local resources for reintegration",
      "Limit services",
      "Reduce family role",
    ],
    correctAnswer: "Use local resources for reintegration",
  },
  {
    id: uuidv4(),
    text: "A major barrier to rehabilitation success is:",
    options: [
      "Family support",
      "Depression",
      "Early intervention",
      "Motivation",
    ],
    correctAnswer: "Depression",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation nursing uses which approach?",
    options: [
      "Disease-centered",
      "Holistic approach",
      "Task-based",
      "Acute care",
    ],
    correctAnswer: "Holistic approach",
  },
  {
    id: uuidv4(),
    text: "Which patient is NOT suitable for intensive rehab?",
    options: [
      "Motivated patient",
      "Medically unstable patient",
      "Family support",
      "Mild disability",
    ],
    correctAnswer: "Medically unstable patient",
  },
  {
    id: uuidv4(),
    text: "The nurse promotes safety in rehab by:",
    options: [
      "Limiting activity",
      "Fall prevention strategies",
      "Bed rest",
      "Isolation",
    ],
    correctAnswer: "Fall prevention strategies",
  },
  {
    id: uuidv4(),
    text: "Which outcome indicates successful stroke rehabilitation?",
    options: [
      "Normal imaging",
      "Improved ability to perform ADLs",
      "Discharge early",
      "No medications",
    ],
    correctAnswer: "Improved ability to perform ADLs",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation plans should be reviewed:",
    options: ["Yearly", "Regularly and adjusted", "At discharge only", "Never"],
    correctAnswer: "Regularly and adjusted",
  },
  {
    id: uuidv4(),
    text: "Which intervention helps prevent contractures?",
    options: [
      "Immobilization",
      "Range-of-motion exercises",
      "Bed rest",
      "Sedation",
    ],
    correctAnswer: "Range-of-motion exercises",
  },
  {
    id: uuidv4(),
    text: "The nurse supports psychosocial rehab by:",
    options: [
      "Ignoring emotions",
      "Active listening",
      "Limiting interaction",
      "Isolation",
    ],
    correctAnswer: "Active listening",
  },
  {
    id: uuidv4(),
    text: "Which patient benefit reflects rehab success?",
    options: [
      "Increased dependence",
      "Enhanced quality of life",
      "Longer hospital stay",
      "Reduced mobility",
    ],
    correctAnswer: "Enhanced quality of life",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation nursing is continuous because:",
    options: [
      "Cure is impossible",
      "Patient needs evolve",
      "It is expensive",
      "It replaces acute care",
    ],
    correctAnswer: "Patient needs evolve",
  },
  {
    id: uuidv4(),
    text: "Which device assists ambulation in partial paralysis?",
    options: ["Hearing aid", "Crutches", "Feeding tube", "Splint"],
    correctAnswer: "Crutches",
  },
  {
    id: uuidv4(),
    text: "A multidisciplinary rehab team ensures:",
    options: [
      "Delayed care",
      "Comprehensive management",
      "Higher cost only",
      "Duplication",
    ],
    correctAnswer: "Comprehensive management",
  },
  {
    id: uuidv4(),
    text: "Rehabilitation focuses on abilities rather than:",
    options: ["Strength", "Disabilities", "Skills", "Potential"],
    correctAnswer: "Disabilities",
  },
  {
    id: uuidv4(),
    text: "The ultimate aim of rehabilitation nursing is to:",
    options: [
      "Cure disease",
      "Enable optimal functional independence",
      "Shorten stay",
      "Reduce costs",
    ],
    correctAnswer: "Enable optimal functional independence",
  },
];
